### ISSUE TITLE
Doesn't create output directory recursively on Windows

### ISSUE THREAD

**Issue by merceyz** [evanw/esbuild#1399]
**Describe the bug**

Building on Windows throws if the output folder doesn't exist and has depth of more than one while on Ubuntu it's fine.

```sh
$ node build.js
 > error: Failed to create output directory: mkdir C:\esbuild-test\foo\bar: No such file or directory

C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1643
        throw err;
        ^

Error: Build failed with 1 error:
error: Failed to create output directory: mkdir C:\esbuild-test\foo\bar: No such file or directory
    at failureErrorWithLog (C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1449:15)
    at C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1131:28
    at runOnEndCallbacks (C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1049:65)
    at buildResponseToResult (C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1129:7)
    at C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1236:14
    at C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:609:9
    at handleIncomingPacket (C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:706:9)
    at readFromStdout (C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:576:7)
    at runServiceSync (C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1814:3)
    at Object.buildSync (C:\esbuild-test\node_modules\esbuild-wasm\lib\main.js:1634:3) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'Failed to create output directory: mkdir C:\\esbuild-test\\foo\\bar: No such file or directory'    }
  ],
  warnings: []
}
```

Ref https://github.com/yarnpkg/berry/pull/2980

**To Reproduce**

```js
const esbuild = require("esbuild-wasm");

esbuild.buildSync({
  entryPoints: ["./test.js"],
  outfile: "foo/bar/baz.js",
});

```

**Environment**

 - OS: Windows 10
 - Node version 16.4.0
 - esbuild version 0.12.9

**Comment by evanw** [comment]
Thanks for the report. It turns out this is a long-standing bug in Go; `os.MkdirAll` doesn't work on Windows. It's another form of https://github.com/golang/go/issues/43768 which I reported a while ago, and which I think is unlikely to be fixed. I will work around it instead.
