### ISSUE TITLE
Panic using esbuild 0.12.12

### ISSUE THREAD

**Issue by chrarnoldus** [evanw/esbuild#1413]
I just got this when trying to build using esbuild 0.12.12. The issue is NOT reproducible (most of time the build succeeds just fine).

```
  panic: Internal error [recovered]
  	panic: Internal error
  
  goroutine 22 [running]:
  github.com/evanw/esbuild/internal/js_parser.Parse.func1(0xc000b25210)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:13673 +0x73
  panic(0x6e0220, 0x7f8e00)
  	runtime/panic.go:965 +0x1c7
  github.com/evanw/esbuild/internal/js_ast.ConvertBindingToExpr(0x1ec, 0x7feaa0, 0xc000292248, 0xc000b21668, 0xc0007601c0, 0x1c0, 0x1b0)
  	github.com/evanw/esbuild/internal/js_ast/js_ast.go:2111 +0x85b
  github.com/evanw/esbuild/internal/js_parser.(*parser).maybeRelocateVarsToTopLevel(0xc0003f2800, 0xc00044aae0, 0x1, 0x1, 0xc00044aa00, 0x1, 0x1, 0x3, 0xc0007601c0)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:9243 +0x14f
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitAndAppendStmt(0xc0003f2800, 0xc000110480, 0x0, 0xc, 0x1df000001e8, 0x7ff280, 0xc000309160, 0x0, 0x0, 0x0)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:8712 +0x28e5
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmts(0xc0003f2800, 0xc0003fe180, 0xc, 0x10, 0x203000100000000, 0xc0006185c0, 0xc00074c210, 0x1df7a9eac00)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:7016 +0x16eb
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitAndAppendStmt(0xc0003f2800, 0xc000802c00, 0x0, 0x1, 0xc0000001e7, 0x7fef80, 0xc0004385b8, 0x0, 0x0, 0x0)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:8768 +0x6a5
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmts(0xc0003f2800, 0xc000b23418, 0x1, 0x1, 0xc000932700, 0xf0, 0xf0, 0xc0003f2978)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:7016 +0x16eb
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitSingleStmt(0xc0003f2800, 0xc0000001e7, 0x7fef80, 0xc0004385b8, 0xc000000100, 0x7feb80, 0xc0003f05c0, 0x0)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:7871 +0xf4
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitAndAppendStmt(0xc0003f2800, 0xc000802be8, 0x0, 0x1, 0x1bd, 0x7ff200, 0xc0000e20f0, 0x0, 0x0, 0x0)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:8834 +0x303f
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmts(0xc0003f2800, 0xc000802bd0, 0x1, 0x1, 0x2030000, 0x2030002, 0x20, 0x7f537e)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:7016 +0x16eb
  github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmtsAndPrependTempRefs(0xc0003f2800, 0xc000802bd0, 0x1, 0x1, 0x0, 0xc00076c000, 0x740000c000802bb8, 0x1, 0x1)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:6929 +0xf8
  github.com/evanw/esbuild/internal/js_parser.(*parser).appendPart(0xc0003f2800, 0xc00076c000, 0xe, 0x10, 0xc000802bd0, 0x1, 0x1, 0xc00076c000, 0xe, 0x10)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:13090 +0x10f
  github.com/evanw/esbuild/internal/js_parser.Parse(0x3, 0xc00044a6f0, 0xc000438348, 0x789ce0, 0xc0004383a8, 0x13, 0xc0004c4230, 0x69, 0x76331b, 0x4, ...)
  	github.com/evanw/esbuild/internal/js_parser/js_parser.go:13838 +0xf25
  github.com/evanw/esbuild/internal/cache.(*JSCache).Parse(0xc0003240a8, 0x4, 0xc000326000, 0xc00030c0a8, 0xc00030c0c0, 0xc000308080, 0x13, 0xc0004c4230, 0x69, 0x76331b, ...)
  	github.com/evanw/esbuild/internal/cache/cache_ast.go:170 +0x318
  github.com/evanw/esbuild/internal/bundler.parseFile(0x807e80, 0xc000336040, 0x4, 0xc000326000, 0xc00030c0a8, 0xc00030c0c0, 0xc000308080, 0x804b98, 0xc000382380, 0xc000324060, ...)
  	github.com/evanw/esbuild/internal/bundler/bundler.go:175 +0x2678
  created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
  	github.com/evanw/esbuild/internal/bundler/bundler.go:1134 +0x638
```

Config used:

```js
require("esbuild").build({
        entryPoints: ["./ClientApp/boot-client.tsx"],
        tsconfig: './tsconfig.json',
        bundle: true,
        minify: true,
        sourcemap: true,
        loader: {
                '.png': "dataurl",
                '.svg': "dataurl",
                '.woff': "file",
                '.woff2': "dataurl",
                '.eot': "file",
                '.ttf': "file",
            },
        outfile: "wwwroot/dist/site.js",
    }).catch(() => process.exit(1));
```

**Comment by evanw** [comment]
Interesting. This indicates that an internal invariant was violated, which is a bug. Is there a way to either provide a reduced test case here that would allow me to reproduce the issue, or somehow provide the code that causes the issue?

Another way to get more information could be to [build esbuild from source](https://esbuild.github.io/getting-started/#build-from-source) after applying this patch:

<details>

<summary>
Click here to show the patch.
</summary>

```diff
diff --git a/internal/bundler/linker.go b/internal/bundler/linker.go
index f4821914..d5fa3658 100644
--- a/internal/bundler/linker.go
+++ b/internal/bundler/linker.go
@@ -3682,7 +3682,7 @@ func (c *linkerContext) generateCodeForFileInChunkJS(
                                        }
                                        var value js_ast.Expr
                                        for _, decl := range s.Decls {
-                                               binding := js_ast.ConvertBindingToExpr(decl.Binding, wrapIdentifier)
+                                               binding := js_ast.ConvertBindingToExpr(decl.Binding, wrapIdentifier, file.InputFile.Source)
                                                if decl.ValueOrNil.Data != nil {
                                                        value = js_ast.JoinWithComma(value, js_ast.Assign(binding, decl.ValueOrNil))
                                                }
diff --git a/internal/js_ast/js_ast.go b/internal/js_ast/js_ast.go
index 611d0f93..7a782c96 100644
--- a/internal/js_ast/js_ast.go
+++ b/internal/js_ast/js_ast.go
@@ -1,6 +1,7 @@
 package js_ast
 
 import (
+       "fmt"
        "math"
        "sort"
 
@@ -2057,7 +2058,7 @@ func EnsureValidIdentifier(base string) string {
        return string(bytes)
 }
 
-func ConvertBindingToExpr(binding Binding, wrapIdentifier func(logger.Loc, Ref) Expr) Expr {
+func ConvertBindingToExpr(binding Binding, wrapIdentifier func(logger.Loc, Ref) Expr, source logger.Source) Expr {
        loc := binding.Loc
 
        switch b := binding.Data.(type) {
@@ -2073,7 +2074,7 @@ func ConvertBindingToExpr(binding Binding, wrapIdentifier func(logger.Loc, Ref)
        case *BArray:
                exprs := make([]Expr, len(b.Items))
                for i, item := range b.Items {
-                       expr := ConvertBindingToExpr(item.Binding, wrapIdentifier)
+                       expr := ConvertBindingToExpr(item.Binding, wrapIdentifier, source)
                        if b.HasSpread && i+1 == len(b.Items) {
                                expr = Expr{Loc: expr.Loc, Data: &ESpread{Value: expr}}
                        } else if item.DefaultValueOrNil.Data != nil {
@@ -2089,7 +2090,7 @@ func ConvertBindingToExpr(binding Binding, wrapIdentifier func(logger.Loc, Ref)
        case *BObject:
                properties := make([]Property, len(b.Properties))
                for i, property := range b.Properties {
-                       value := ConvertBindingToExpr(property.Value, wrapIdentifier)
+                       value := ConvertBindingToExpr(property.Value, wrapIdentifier, source)
                        kind := PropertyNormal
                        if property.IsSpread {
                                kind = PropertySpread
@@ -2108,6 +2109,8 @@ func ConvertBindingToExpr(binding Binding, wrapIdentifier func(logger.Loc, Ref)
                }}
 
        default:
-               panic("Internal error")
+               tracker := logger.MakeLineColumnTracker(&source)
+               location := logger.LocationOrNil(&tracker, logger.Range{Loc: binding.Loc})
+               panic(fmt.Sprintf("Internal error in file %s on line %d", source.PrettyPath, location.Line))
        }
 }
diff --git a/internal/js_parser/js_parser.go b/internal/js_parser/js_parser.go
index 2235d85d..69674c58 100644
--- a/internal/js_parser/js_parser.go
+++ b/internal/js_parser/js_parser.go
@@ -8692,7 +8692,7 @@ func (p *parser) visitAndAppendStmt(stmts []js_ast.Stmt, stmt js_ast.Stmt) []js_
                        }
                        for _, decl := range s.Decls {
                                if decl.ValueOrNil.Data != nil {
-                                       target := js_ast.ConvertBindingToExpr(decl.Binding, wrapIdentifier)
+                                       target := js_ast.ConvertBindingToExpr(decl.Binding, wrapIdentifier, p.source)
                                        if result, ok := p.lowerAssign(target, decl.ValueOrNil, objRestReturnValueIsUnused); ok {
                                                target = result
                                        } else {
@@ -9240,7 +9240,7 @@ func (p *parser) maybeRelocateVarsToTopLevel(decls []js_ast.Decl, mode relocateV
        }
        var value js_ast.Expr
        for _, decl := range decls {
-               binding := js_ast.ConvertBindingToExpr(decl.Binding, wrapIdentifier)
+               binding := js_ast.ConvertBindingToExpr(decl.Binding, wrapIdentifier, p.source)
                if decl.ValueOrNil.Data != nil {
                        value = js_ast.JoinWithComma(value, js_ast.Assign(binding, decl.ValueOrNil))
                } else if mode == relocateVarsForInOrForOf {
diff --git a/internal/js_parser/js_parser_lower.go b/internal/js_parser/js_parser_lower.go
index 442c1c72..3bf0f842 100644
--- a/internal/js_parser/js_parser_lower.go
+++ b/internal/js_parser/js_parser_lower.go
@@ -283,7 +283,7 @@ func (p *parser) lowerFunction(
                for i, arg := range *args {
                        if bindingHasObjectRest(arg.Binding) {
                                ref := p.generateTempRef(tempRefNoDeclare, "")
-                               target := js_ast.ConvertBindingToExpr(arg.Binding, nil)
+                               target := js_ast.ConvertBindingToExpr(arg.Binding, nil, p.source)
                                init := js_ast.Expr{Loc: arg.Binding.Loc, Data: &js_ast.EIdentifier{Ref: ref}}
                                p.recordUsage(ref)
 
@@ -1180,7 +1180,7 @@ func (p *parser) lowerObjectRestInDecls(decls []js_ast.Decl) []js_ast.Decl {
                        clone := append([]js_ast.Decl{}, decls[:i]...)
                        for _, decl := range decls[i:] {
                                if decl.ValueOrNil.Data != nil {
-                                       target := js_ast.ConvertBindingToExpr(decl.Binding, nil)
+                                       target := js_ast.ConvertBindingToExpr(decl.Binding, nil, p.source)
                                        if result, ok := p.lowerObjectRestToDecls(target, decl.ValueOrNil, clone); ok {
                                                clone = result
                                                continue
```

</details>

That should point to exactly the input that triggers this bug which could help in creating a minimal test case that reproduces the issue.

**Comment by kzc** [comment]
> The issue is NOT reproducible (most of time the build succeeds just fine).

Where could non-determinism potentially occur in a parse? Although parsing happens in parallel, each individual parse appears to be independent and share nothing to produce an AST.

**Comment by evanw** [comment]
Like you said parsing is serial, not parallel, and the crash is in the parser so it's strange for it to be non-deterministic. There is technically non-determinism when you iterate over a map in Go so that could in theory be the reason this happens. It's hard to say without more information though.

**Comment by kzc** [comment]
It's not clear whether array `append` is deterministic with respect to increasing capacity:

"If the capacity of s is not large enough to fit the additional values, append allocates a new, sufficiently large underlying array that fits both the existing slice elements and the additional values."
https://golang.org/ref/spec#Appending_and_copying_slices

If not it might affect array aliases and slices.

**Comment by chrarnoldus** [comment]
I ran the patched executable in a loop for many hours, but haven't seen the crash since. So sadly I don't have any additional information currently.

Perhaps worth mentioning: the crash happened on a machine with a lot of cores (32). It's a long shot, but maybe that makes some issue slightly more likely to trigger?

**Comment by kzc** [comment]
Could the patch be committed to git? It seems to not incur much overhead and may be helpful in the rare event of a panic.

**Comment by chrarnoldus** [comment]
We are still getting non-reproducible errors occasionally, but the exact error message is different most/all of the time. For example, we did get this error message recently:

```
panic : runtime error : invalid memory address or nil pointer dereference
  [signal 0xc0000005 code=0x1 addr=0x0 pc=0x13986b]
  
  goroutine 9 [running]:
  github.com/evanw/esbuild/internal/css_parser.(*parser).parseComplexSelector(0xc000625840)
  	github.com/evanw/esbuild/internal/css_parser/css_parser_selector.go:41 +0x131
  github.com/evanw/esbuild/internal/css_parser.(*parser).parseSelectorList(0xc000625840)
  	github.com/evanw/esbuild/internal/css_parser/css_parser_selector.go:11 +0x95
  github.com/evanw/esbuild/internal/css_parser.(*parser).parseSelectorRule(0xc000625840)
  	github.com/evanw/esbuild/internal/css_parser/css_parser.go:937 +0x2e
  github.com/evanw/esbuild/internal/css_parser.(*parser).parseListOfRules(0xc000625840, {0x0, 0x47})
  	github.com/evanw/esbuild/internal/css_parser/css_parser.go:227 +0x252
  github.com/evanw/esbuild/internal/css_parser.Parse({0x3, 0xc000300120, 0xc00030c120, 0x544788, 0xc00030c150}, {0x2, {{0xc000214700, 0x69}, {0x51d601, 0x4}, ...}, ...}, ...)
  	github.com/evanw/esbuild/internal/css_parser/css_parser.go:47 +0x32b
  github.com/evanw/esbuild/internal/cache.(*CSSCache).Parse(0xc00031e088, {0x4, 0xc000320000, 0xc00030c0a8, 0xc00030c0c0, 0xc000308080}, {0x2, {{0xc000214700, 0x69}, {0x51d601, ...}, ...}, ...}, ...)
  	github.com/evanw/esbuild/internal/cache/cache_ast.go:59 +0x258
  github.com/evanw/esbuild/internal/bundler.parseFile({{0x5c8810, 0xc00032c040}, {0x4, 0xc000320000, 0xc00030c0a8, 0xc00030c0c0, 0xc000308080}, {0x5c2338, 0xc000380380}, 0xc00031e060, ...})
  	github.com/evanw/esbuild/internal/bundler/bundler.go:200 +0x27e5
  created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
  	github.com/evanw/esbuild/internal/bundler/bundler.go:1123 +0x7e5
```
