### ISSUE TITLE
Circular dependency issue 

### ISSUE THREAD

**Issue by mfbx9da4** [evanw/esbuild#1582]
```ts
// app.ts
import { foo } from './foo'
import { baz } from './bar'

export function app() {
  foo()
  baz()
}

app()

// foo.ts
import { bar } from './bar'
export const foo = () => {
  console.log('bar()', bar())
}

// bar.ts
import { foo } from './foo'
export const bar = () => {
  return 1
}

export const baz = foo
```

```
npx esbuild app.ts --bundle --platform=node --target=node14.6 > out.js && node out.js
```

```js
var __defProp = Object.defineProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// app.ts
__export(exports, {
  app: () => app
});

// bar.ts
var bar = () => {
  return 1;
};
var baz = foo;

// foo.ts
var foo = () => {
  console.log("bar()", bar());
};

// app.ts
function app() {
  foo();
  baz();
}
app();
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  app
});
```

This throws the following runtime error

```
bar() 1
/Users/asdf/esbuild-issue/out.js:28
  baz();
  ^

TypeError: baz is not a function
    at app (/Users/asdf/esbuild-issue/out.js:28:3)
    at Object.<anonymous> (/Users/asdf/esbuild-issue/out.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

```

This should at least throw a compile time error like node 

```
file:///Users/asdf/esbuild-issue/bar.js:6
export const baz = foo
                   ^

ReferenceError: Cannot access 'foo' before initialization
    at file:///Users/asdf/esbuild-issue/bar.js:6:20
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

```

**Comment by evanw** [comment]
This is a problem with your code, not with esbuild. Use a compile-time binding such as `export { foo as baz }` instead of a run-time binding such as `export const baz = foo` if you want the binding to happen at compile-time instead of at run-time.

> This should at least throw a compile time error like node

This error in node is also a run-time error, not a compile-time error. Notice how the error message has a stack trace that indicates the code is in the middle of being run.

Closing as esbuild is working correctly.
