### ISSUE TITLE
Syntax Error: Identifier 'pool' has already been declared

### ISSUE THREAD

**Issue by Fargath15** [evanw/esbuild#1605]
Const pool = new pool gives error

**Comment by Fargath15** [comment]
server.js

code:
const express = require("express");
const studentRoutes = require("./src/student/routes");
const pool = require("./db");

const app = express();
const port = 3000;

app.use(express.json());

app.get("/", (req, res) => {
    res.send("Hello World!");
});

app.use("/api/v1/students", studentRoutes);

app.listen(port,() => console.log(`app listening on port ${port}`));



db.js 
code:

const pool = require("pg").pool;

const pool = new pool({
    user: "postgres",
    host : "localhost",
    database: "students",
    password: "Manas@1506",
    port: 8080,
});

module.exports = pool;

error:

PS C:\Users\elcot\restapi> node .\server.js
C:\Users\elcot\restapi\db.js:3
const pool = new pool({
      ^

SyntaxError: Identifier 'pool' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\elcot\restapi\src\student\controller.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by hyrious** [comment]
You can't declare a const twice:
```js
const pool = require("pg").pool;
const pool = new pool({
```
Neither can this:
```js
let a = 1
let a = a + 1
```
You may have a typo in your code as I saw the package `pg` has an export called `Pool` (note the case).

**Comment by Fargath15** [comment]
Thanks for helping. i am a beginner and trying to practice
