### ISSUE TITLE
Runtime panic in v0.4.3

### ISSUE THREAD

**Issue by DanielHeath** [evanw/esbuild#162]
Running https://registry.yarnpkg.com/esbuild/-/esbuild-0.4.3.tgz#228e108f849128a2b2e64d524235fef58236912b

The error occurs when compiling multiple entry points at once. Compiling them individually does not cause an error.

```
$ ./node_modules/.bin/esbuild --outdir=tmp/esbuild --minify --sourcemap <multiple entry points>
panic: runtime error: index out of range [2] with length 1

goroutine 50 [running]:
github.com/evanw/esbuild/internal/bundler.bitSet.hasBit(...)
	/Users/evan/dev/esbuild/internal/bundler/linker.go:27
github.com/evanw/esbuild/internal/bundler.(*linkerContext).includeFile(0xc0004d2000, 0x11, 0x11, 0xc000000000)
	/Users/evan/dev/esbuild/internal/bundler/linker.go:1004 +0x92b
github.com/evanw/esbuild/internal/bundler.(*linkerContext).markPartsReachableFromEntryPoints(0xc0004d2000)
	/Users/evan/dev/esbuild/internal/bundler/linker.go:985 +0x219
github.com/evanw/esbuild/internal/bundler.(*linkerContext).link(0xc0004d2000, 0xc0004ba060, 0x7fd1a0, 0xc0000ac2c0)
	/Users/evan/dev/esbuild/internal/bundler/linker.go:345 +0x61
github.com/evanw/esbuild/internal/bundler.(*Bundle).Compile.func1(0xc0004c4000, 0xc0004ba060, 0xc00008a300, 0xc0004c6000, 0x11, 0x11, 0xc0004940e0, 0x10, 0x11)
	/Users/evan/dev/esbuild/internal/bundler/bundler.go:408 +0x136
created by github.com/evanw/esbuild/internal/bundler.(*Bundle).Compile
	/Users/evan/dev/esbuild/internal/bundler/bundler.go:406 +0x1b4
error Command failed with exit code 2.
```

**Comment by evanw** [comment]
I can't reproduce this myself. Can you provide a test case that reproduces this behavior?
