### ISSUE TITLE
bug: Plug-in cannot use regular expressions `new RegExp('^(?!\\.{1,2}\\/)')`

### ISSUE THREAD

**Issue by rxliuli** [evanw/esbuild#1634]
Error stack

```js
Error: [esbuild-plugin-auto-external] "onResolve" filter is not a valid Go regular expression: "^(?!\\.{1,2}\\/)"
    at C:\Users\rxliuli\Code\Pkg\liuli-tools\apps\liuli-cli\node_modules\esbuild\lib\main.js:1237:25
    at C:\Users\rxliuli\Code\Pkg\liuli-tools\apps\liuli-cli\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\Users\rxliuli\Code\Pkg\liuli-tools\apps\liuli-cli\node_modules\esbuild\lib\main.js:724:9)
    at Socket.readFromStdout (C:\Users\rxliuli\Code\Pkg\liuli-tools\apps\liuli-cli\node_modules\esbuild\lib\main.js:596:7)
```

Plug-in source code

```js
function autoExternal(): Plugin {
  return {
    name: 'esbuild-plugin-auto-external',
    setup(build) {
      build.onResolve({ filter: new RegExp('^(?!\\.{1,2}\\/)') }, (args) => {
        console.log('esbuild-plugin-auto-external: ', args.path)
        return {
          path: args.path,
          external: true,
        }
      })
    },
  }
}
```

**Comment by evanw** [comment]
This is because esbuild is written in Go so it uses Go's regular expression syntax. As the error message says, `^(?!\.{1,2}\/)` is not a valid Go regular expression. Go's regular expression syntax is documented here: https://pkg.go.dev/regexp which links to here: https://github.com/google/re2/wiki/Syntax. There you will find this:

> | | Empty strings |
> |---|---|
> | `(?!re)` | before text not matching `re` (NOT SUPPORTED) |

JavaScript supports more regular expression features than Go. If you want to use JavaScript regular expression features you can just use `/.*/` for the feature passed to esbuild and then run the JavaScript regular expression yourself in the callback (although it will of course be slower since it means Go must call out to JavaScript).

**Comment by evanw** [comment]
Closing as this is a known limitation, not a bug, and there is a straightforward workaround.

**Comment by alxroyer** [comment]
@rxliuli, @evanw, just to be sure I fully understand the workaround identified above.

@evanw says that we can test a JavaScript regular expression "in the callback".
I understand that this "callback" is the one defined in the esbuild plugin.
Am I right?

I also understand that you, @rxliuli, may have implemented such workaround in your plugin?
But we can't assume that every plugin available in the esbuild ecosystem did so?
Furthermore, as a user of a third-party plugin, I may not wish to change the behaviour of this callback.
Am I right again?

Just in order to check whether this [esbuild-plugin-filter-callback](https://github.com/alxroyer/esbuild-plugin-filter-callback) could be of interest for the esbuild community?
Or maybe there is a simpler way to define advanced filters.

Thanks.

**Comment by evanw** [comment]
> @evanw says that we can test a JavaScript regular expression "in the callback".
> I understand that this "callback" is the one defined in the esbuild plugin.
> Am I right?

Yes. If this doesn't work:

```js
build.onResolve({ filter: /some stuff/ }, (args) => {
  ...
})
```

then you can do this instead:

```js
build.onResolve({ filter: /.*/ }, (args) => {
  if (!/some stuff/.test(args.path)) return;
  ...
})
```

**Comment by alxroyer** [comment]
Thanks @evanw.

Yes it works, but as far as I understand, these lines appear inside the plugin only.

And as a user of a third-party plugin, I may not be able to easily setup such filtering code on the Javascript side, unless:
- contributing to the plugin,
- or wrapping the plugin (the purpose of my [esbuild-plugin-filter-callback](https://github.com/alxroyer/esbuild-plugin-filter-callback) proposal).
