### ISSUE TITLE
exclude node_modules from source map

### ISSUE THREAD

**Issue by sushantdhiman** [evanw/esbuild#1685]
Is there a way to exclude a folder from source maps while keeping files in bundle.

Similar issues

- https://github.com/evanw/esbuild/issues/1227, but I want to ignore entire `node_modules` folder instead of a single file.
- https://github.com/webpack/webpack/issues/2431, for webpack

**Background:**

My source maps are too big even with `sourcesContent: false` (I only need stack-traces). Big source maps take some time to load with `node --enable-source-maps`

![image](https://user-images.githubusercontent.com/9989487/137577039-c4b65b33-8700-44c0-8dbf-4ef4fab3f217.png)

**Comment by evanw** [comment]
Here is a plugin that does what #1227 does but for anything with `node_modules` in the path:

```js
let plugin = {
  name: 'excludeVendorFromSourceMap',
  setup(build) {
    build.onLoad({ filter: /node_modules/ }, args => {
      return {
        contents: fs.readFileSync(args.path, 'utf8')
          + '\n//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIiJdLCJtYXBwaW5ncyI6IkEifQ==',
        loader: 'default',
      }
    })
  },
}
```

Feel free to customize the plugin further for your needs. You can read more about esbuild plugins here: https://esbuild.github.io/plugins/.

**Comment by philllies** [comment]
> ```js
> let plugin = {
>   name: 'excludeVendorFromSourceMap',
>   setup(build) {
>     build.onLoad({ filter: /node_modules/ }, args => {
>       return {
>         contents: fs.readFileSync(args.path, 'utf8')
>           + '\n//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIiJdLCJtYXBwaW5ncyI6IkEifQ==',
>         loader: 'default',
>       }
>     })
>   },
> }
> ```

use this gives me the following error:
```
 > ../../node_modules/redis-commands/commands.json:2335:0: error: JSON does not support comments
    2335 │ //# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIiJdLCJtYXBwaW5ncyI6IkEifQ==
```

**Comment by slootjes** [comment]
While the plugin looks great at first sight as it indeed reduces the bundle size a lot, it however breaks the sourcemap (at least it does on AWS Lambda/CloudWatch):

without plugin (larger bundle size + slow loading):
```
{
  type: 'http',
  error: TypeError: Cannot read properties of undefined (reading 'id')
      at Function.unserialize (/node_modules/{package}/src/{something}/{something}.ts:12:54)
      at Function.unserialize (/node_modules/{package}/src/{something}/{something}.ts:31:19)
      at <anonymous> (/src/Handler/Http/Api.ts:17:31)
      at <anonymous> (/node_modules/lambda-api/index.js:303:29)
      at new Promise (<anonymous>)
      at API.run (/node_modules/lambda-api/index.js:301:15)
}

```
with plugin (small bundle size, fast loading):
```
{
  type: 'http',
  error: TypeError: Cannot read properties of undefined (reading 'id')
      at Function.unserialize (/node_modules/@aws-sdk/client-dynamodb/package.json:106:1) <- incorrect
      at Function.unserialize (/node_modules/@aws-sdk/client-dynamodb/package.json:106:1) <- incorrect
      at <anonymous> (/src/Handler/Http/Api.ts:17:31)
      at <anonymous> (/node_modules/@aws-sdk/client-sso-oidc/package.json:99:1) <- incorrect
      at new Promise (<anonymous>)
      at API.run (/node_modules/@aws-sdk/client-sso-oidc/package.json:99:1) <- incorrect
}
```

The source map becomes quite useless this way. Am I missing somethere here?

**Comment by zach-betz-hln** [comment]
I came here from [this comment](https://github.com/nodejs/node/issues/41541#issuecomment-1457485140).

After enabling the `--enable-source-maps` flag, some of our node apps doubled in memory usage (measured directly after startup).

Using your plugin to make the source map file smaller did the trick to lower memory usage to expected levels 👍 

The file went from 9.8mb to 493.1kb. Thank you. 

<details><summary>Modified plugin</summary>

```js
const excludeVendorFromSourceMapPlugin = {
  name: 'excludeVendorFromSourceMapPlugin',
  setup(build) {
    build.onLoad({ filter: /node_modules/ }, (args) => {
      const isSourceFile = ['.js', '.ts'].some((ext) => args.path.endsWith(ext));

      if (!isSourceFile) {
        return;
      }

      const sourceMap = { version: 3, sources: [''], mappings: 'A' };
      const base64 = Buffer.from(JSON.stringify(sourceMap)).toString('base64');
      return {
        contents: `${fs.readFileSync(args.path, 'utf8')}\n//# sourceMappingURL=data:application/json;base64,${base64}`,
        loader: 'default'
      };
    });
  }
};
```

</details>

**Comment by UltimateGG** [comment]
For anyone here on a more recent version of esbuild, the plugin will have no affect with the empty source map. It must have 4 A's to work.
https://github.com/evanw/esbuild/issues/4130#issuecomment-2788327801

That one will work
