### ISSUE TITLE
TypeError: Cannot convert undefined or null to object while trying to analyze metadata

### ISSUE THREAD

**Issue by kaiyoma** [evanw/esbuild#1696]
I was able to convert a small package of mine from Rollup to esbuild, but as soon as I added a call to `analyzeMetafile` (following the example [here](https://esbuild.github.io/api/#analyze)), I started getting a crash:

```
$ node --trace-warnings esbuild.config.js
(node:15836) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at visit (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:81:25)
    at visit (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:86:9)
    at encodePacket (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:93:3)
    at sendRequest (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:637:27)
    at Object.analyzeMetafile2 [as analyzeMetafile] (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1369:5)
    at C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1940:55
    at new Promise (<anonymous>)
    at Object.analyzeMetafile (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1940:14)
    at Object.analyzeMetafile (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1753:71)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:15836) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at visit (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:81:25)
    at visit (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:86:9)
    at encodePacket (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:93:3)
    at sendRequest (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:637:27)
    at Object.analyzeMetafile2 [as analyzeMetafile] (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1369:5)
    at C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1940:55
    at new Promise (<anonymous>)
    at Object.analyzeMetafile (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1940:14)
    at Object.analyzeMetafile (C:\Work\web-components\common\temp\node_modules\.pnpm\esbuild@0.13.8\node_modules\esbuild\lib\main.js:1753:71)
(node:15836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by kaiyoma** [comment]
> This is because some object's value in the metafile becomes `undefined`, which should not happen on current [metafile](https://esbuild.github.io/api/#metafile) structure. Can you provide a reproduce-able code?

Not easily, as this is a large proprietary codebase. Happy to help out if you have other debugging suggestions or if I can get you other info.

**Comment by evanw** [comment]
Closing due to lack of a response.

**Comment by connorjs** [comment]
> Make sure you are passing `metafile: true` to `esbuild.build()` so that a metafile is generated.

Thanks! Adding `metafile: true` fixed this error when I encountered it.
