### ISSUE TITLE
Error on Apple M1 chip

### ISSUE THREAD

**Issue by dspacejs** [evanw/esbuild#1775]
I'm getting the following error with the vite CLI:

```
failed to load config from /Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/vite.config.js
error when starting dev server:
Error: The package "esbuild-darwin-arm64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
    at generateBinPath (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/esbuild/lib/main.js:1643:15)
    at esbuildCommandAndArgs (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/esbuild/lib/main.js:1699:11)
    at ensureServiceIsRunning (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/esbuild/lib/main.js:1856:25)
    at Object.build (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/esbuild/lib/main.js:1749:26)
    at bundleConfigFile (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:68658:34)
    at loadConfigFromFile (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:68635:35)
    at resolveConfig (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:68185:34)
    at createServer (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:66699:26)
    at CAC.<anonymous> (/Users/daniel/Documents/Dev/freelance/privacy-dynamics/analyzer-app/webapp/node_modules/vite/dist/node/cli.js:687:30)
```

I tried installing esbuild globally with `npm install -g esbuild` (which seemed to fix some errors for Linux machines in another thread), but that didn't work.

**Comment by UrsulaYZ** [comment]
Do you resolve it ?

**Comment by ohlyf** [comment]
> 



> Do you resolve it ?

use new version node or add esbuild-darwin-arm64
