### ISSUE TITLE
panic after warning of missing semi-colon for css @import

### ISSUE THREAD

**Issue by sbfaulkner** [evanw/esbuild#1803]
The following CSS causes a panic when esbuild tries to process it...

```
@import url("fonts.css")

.one {
	background: url("one.jpg");
}

.two {
	background: url("two.jpg");
}
```

### the panic…
```
$ bin/esbuild --loader=css --minify <style.css
 > style.css:9:1: warning: Expected ";"
    9 │ }
      ╵  ^

panic: runtime error: index out of range [1] with length 1

goroutine 10 [running]:
github.com/evanw/esbuild/internal/css_printer.(*printer).printTokens(0xc0000bf420, {0xc000222100, 0x4, 0x7301040000}, {0x10, 0x0})
	/Users/sbfaulkner/src/github.com/evanw/esbuild/internal/css_printer/css_printer.go:694 +0xcb9
github.com/evanw/esbuild/internal/css_printer.(*printer).printTokens(0xc0000bf420, {0xc000224000, 0x6, 0x0}, {0x0, 0x0})
	/Users/sbfaulkner/src/github.com/evanw/esbuild/internal/css_printer/css_printer.go:704 +0xa5e
github.com/evanw/esbuild/internal/css_printer.(*printer).printRule(0xc0000bf420, {{0x0}, {0x1512c88, 0xc000020840}}, 0x0, 0x0)
	/Users/sbfaulkner/src/github.com/evanw/esbuild/internal/css_printer/css_printer.go:104 +0x1058
github.com/evanw/esbuild/internal/css_printer.Print({{0xc00003c840, 0x1, 0x1}, {0xc00000e9a8, 0x1, 0x1}, {{0x0, 0x0}, {{0x0}, 0x0}}, ...}, ...)
	/Users/sbfaulkner/src/github.com/evanw/esbuild/internal/css_printer/css_printer.go:54 +0x305
github.com/evanw/esbuild/internal/bundler.(*linkerContext).generateChunkCSS(0xc00017b040, {0xc0000dd080, 0x1, 0x1}, 0x0, 0xc00002b850)
	/Users/sbfaulkner/src/github.com/evanw/esbuild/internal/bundler/linker.go:4882 +0xe38
created by github.com/evanw/esbuild/internal/bundler.(*linkerContext).generateChunksInParallel
	/Users/sbfaulkner/src/github.com/evanw/esbuild/internal/bundler/linker.go:356 +0x46f
```

NOTE: our actual failure is in a service that invokes the go pkg directly -- not the CLI

**Comment by sbfaulkner** [comment]
I'm guessing the parsing issue is that the parsing of conditions for an `@import` is a bit too lax...
https://github.com/evanw/esbuild/blob/master/internal/css_parser/css_parser.go#L650-L652

(resulting in the "conditions" including the remaining css to eof)
