### ISSUE TITLE
[Bug]: Array buffer allocation failed

### ISSUE THREAD

**Issue by 7086cmd** [evanw/esbuild#1986]
I used `vite` to build front end and processing `css`, but it always says that `Array buffer allocation failed` in workflow.

here are the result:
```shell
D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:148
      let clone = new Uint8Array((this.len + delta) * 2);
                  ^
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at ByteBuffer._write (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:148:19)
    at ByteBuffer.write32 (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:160:23)
    at visit (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:83:10)
    at visit (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:86:9)
    at visit (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:78:9)
    at visit (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:86:9)
    at encodePacket (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:93:3)
    at sendRequest (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:637:27)
    at Object.formatMessages2 [as formatMessages] (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1348:5)
    at D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1931:55
    at new Promise (<anonymous>)
    at Object.formatMessages (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1931:14)
    at Object.formatMessages (D:\a\magnifique\magnifique\node_modules\.pnpm\esbuild@0.13.15\node_modules\esbuild\lib\main.js:1752:70)
    at minifyCSS (D:\a\magnifique\magnifique\node_modules\.pnpm\vite@2.7.1_less@4.1.2\node_modules\vite\src\node\plugins\css.ts:915:24)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

and it always says that 
```shell
 > <stdin>:1:168962: warning: "@charset" must be the first rule in the file
    1 │ ...t-align:right;margin-top:8px}@charset "UTF-8";.el-upload{display:i...
      ╵                                 ~~~~~~~~
   <stdin>:1:168907: note: This rule cannot come before a "@charset" rule
    1 │ ...opconfirm__icon{margin-right:5px}.el-popconfirm__action{text-align...
      ╵                                     ^
```
in minifying `css`.

Is there any problem in that?

**Comment by hyrious** [comment]
These are 2 problems:

1. <q><samp>RangeError: Array buffer allocation failed</samp></q> may be caused by allocating too huge (or negative) memory. The code doesn't seem to be negative, so maybe the ci machine is only 32-bit and you're allocating a memory bigger than 4GB (in fact, 3.5 GB on windows). And a node process has a default memory limit to about 2GB in my experience. You have to add `--max-old-space-size=6144` to your NODE_OPTIONS to increase that limit to 6GB.

2. This is already known issue there: https://github.com/vitejs/vite/issues/5833#issuecomment-981972639 you can apply this hack to just remove `@charset` statements.

**Comment by 7086cmd** [comment]
Ok, thanks. I will try again soon. If successful, I will close it.

**Comment by 7086cmd** [comment]
ok. everything was ok through [build includes @charset problem. vitejs/vite#5833 (comment)](https://github.com/vitejs/vite/issues/5833#issuecomment-981972639). Thanks.
