### ISSUE TITLE
Web3 import failure

### ISSUE THREAD

**Issue by barberj** [evanw/esbuild#2184]
Unable to resolve modules at build time.

```
 > node_modules/eth-lib/lib/bytes.js:9:201: error: Could not resolve "crypto" (use "--platform=node" when building for node)
    9 │ ... !== "undefined") rnd = require("c" + "rypto").randomBytes(bytes);...
      ╵                                    ~~~

 > node_modules/web3-providers-http/lib/index.js:26:19: error: Could not resolve "http" (use "--platform=node" when building for node)
    26 │ var http = require('http');
       ╵                    ~~~~~~

 > node_modules/web3-providers-http/lib/index.js:27:20: error: Could not resolve "https" (use "--platform=node" when building for node)
    27 │ var https = require('https');
       ╵                     ~~~~~~~

 > node_modules/web3-providers-ws/lib/helpers.js:9:22: error: Could not resolve "url" (use "--platform=node" when building for node)
    9 │     var url = require('url');
      ╵                       ~~~~~

 > node_modules/xhr2-cookies/dist/xml-http-request.js:21:19: error: Could not resolve "http" (use "--platform=node" when building for node)
    21 │ var http = require("http");
       ╵                    ~~~~~~

 > node_modules/web3-eth-accounts/lib/index.js:26:84: error: Could not resolve "crypto" (use "--platform=node" when building for node)
    26 │ ...=== 'undefined') ? require('crypto-browserify') : require('crypto');
       ╵                                                              ~~~~~~~~

 > node_modules/xhr2-cookies/dist/xml-http-request.js:22:20: error: Could not resolve "https" (use "--platform=node" when building for node)
    22 │ var https = require("https");
       ╵                     ~~~~~~~

 > node_modules/xhr2-cookies/dist/xml-http-request.js:23:17: error: Could not resolve "os" (use "--platform=node" when building for node)
    23 │ var os = require("os");
       ╵                  ~~~~

 > node_modules/xhr2-cookies/dist/xml-http-request.js:24:18: error: Could not resolve "url" (use "--platform=node" when building for node)
    24 │ var url = require("url");
       ╵                   ~~~~~

 > node_modules/ethereumjs-util/dist.browser/object.js:7:39: error: Could not resolve "assert" (use "--platform=node" when building for node)
    7 │ var assert_1 = __importDefault(require("assert"));
      ╵                                        ~~~~~~~~
```

Running with Elixir/Phoenix 1.6.7

`package.json`
```
{
  "dependencies": {
    "web3": "^1.7.3"
  }
}
```

esbuild config:
```
# Configure esbuild (the version is required)
config :esbuild,
  version: "0.14.0",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]
```

Standard vanilla install. After phx install I `npm install web3` and imported in `app.js` and getting errors. Please advise. Thanks in advance!

**Comment by barberj** [comment]
if i bump to version `0.14.36` the build errors go away, but i see this in the console:

```
index.js:20 Uncaught ReferenceError: require is not defined
    at node_modules/web3-core-requestmanager/lib/index.js (index.js:20:25)
    at __require (app.js:26:44)
    at node_modules/web3-core/lib/index.js (index.js:22:24)
    at __require (app.js:26:44)
    at node_modules/web3/lib/index.js (index.js:29:12)
    at __require (app.js:26:44)
    at app.js:27:8
```

**Comment by evanw** [comment]
It looks like you are trying to use node libraries outside of node. You can't do that. That doesn't work.

**Comment by barberj** [comment]
Not sure how to get web3 with npm, but i found a precompiled min version on the github repo they reference for use outside of node
