### ISSUE TITLE
`__extends is not a function` when loading bundled typescript through requirejs

### ISSUE THREAD

**Issue by Socolin** [evanw/esbuild#2259]
Hello,

I'm getting an error `__extends is not a function`  when loading script through [requirejs](https://requirejs.org/)

Repro: 

Clone https://github.com/Socolin/repro-esbuild-bug then open `requirejs.html` 
```
test.min.js:1333 Uncaught TypeError: __extends is not a function
    at test.min.js:1333:5
    at test.min.js:1338:4
    at test.min.js:1776:3
```

It works when using `<script>` directly, see `direct.html`:

To rebuild
```shell
npm install
npm run build
```

**Comment by hyrious** [comment]
This is because `tslib` has a UMD wrapper that it detects global `define` and use it instead of `module.exports`, which results in `require_tslib()` returns `{}`, anything from tslib becomes `undefined`.

```js
var require_tslib = __commonJS({
...
// code in tslib, when enabled requirejs,
// there will be global 'define'
(function(factory) {
        var root = typeof global === "object" ? global : typeof self === "object" ? self : typeof this === "object" ? this : {};
        if (typeof define === "function" && define.amd) {
          define("tslib", ["exports"], function(exports2) {
            factory(createExporter(root, createExporter(exports2))); // see, module.exports not used here, so require_tslib() returns {}
          });
        } else if (typeof module === "object" && typeof module.exports === "object") {
          factory(createExporter(root, createExporter(module.exports))); // where there's no requirejs, this module works fine
        } else {
          factory(createExporter(root));
        }
```

**Comment by Socolin** [comment]
Awesome it works !
Thanks a lot for the quick response ! :)
