### ISSUE TITLE
Cannot find module 'node:*'

### ISSUE THREAD

**Issue by vanyauhalin** [evanw/esbuild#2342]
Since of [v18](https://nodejs.org/dist/latest-v18.x/docs/api/console.html#class-console), it is recommended to add a `node` prefix for core modules, but it's not compatible with versions bellow 14. It will be great if the esbuild will remove the prefix for older versions.

```js
// index.js
const { build } = require('esbuild');
(async () => {
  await build({
    allowOverwrite: true,
    entryPoints: ['src.js'],
    outfile: 'dist.js',
    platform: 'node',
    format: 'cjs',
    target: 'node10'
  });
})();
```

```js
// src.js
import { log } from 'node:console';
log('Hello');
```

```js
// dist.js
var import_node_console = require("node:console");
(0, import_node_console.log)("Hello");
```

```txt
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:console'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/esbuild-node/esbuild-node/dist.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

See [sources](https://github.com/vanyauhalin/esbuild-node).

**Comment by evanw** [comment]
You need to enable bundling for esbuild to look at your import paths: https://esbuild.github.io/api/#bundle. Without bundling, import paths are just passed through unmodified.

**Comment by vanyauhalin** [comment]
Got it, thanks!
