### ISSUE TITLE
esbuild-linux-loong64 package not found

### ISSUE THREAD

**Issue by smeng9** [evanw/esbuild#2432]
To reproduce:
I tried to create a vite app using `$ yarn dlx vite testvite --template react`

It returns following error:
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0001: │ TypeError: esbuild-linux-loong64@npm:0.14.52: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ET.getCandidates (/home/motion/.node/corepack/yarn/3.2.1/yarn.js:713:26755)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bd.getCandidates (/home/motion/.node/corepack/yarn/3.2.1/yarn.js:396:1241)
    at async Bd.getCandidates (/home/motion/.node/corepack/yarn/3.2.1/yarn.js:396:1241)
    at async /home/motion/.node/corepack/yarn/3.2.1/yarn.js:442:7756
    at async Rg (/home/motion/.node/corepack/yarn/3.2.1/yarn.js:395:11092)
    at async le (/home/motion/.node/corepack/yarn/3.2.1/yarn.js:442:7738)
    at async Promise.allSettled (index 10)
    at async uo (/home/motion/.node/corepack/yarn/3.2.1/yarn.js:395:10390)
➤ YN0000: └ Completed in 1s 903ms
➤ YN0000: Failed with errors in 1s 905ms

Further investigation suggests the package is published under a different name [@esbuild/linux-loong64](https://www.npmjs.com/package/@esbuild/linux-loong64)

Shall we use the esbuild-linux-loong64 as the package name?

Environment:
Ubuntu 22.04
Node 18.6.0
Yarn 3.2.2
Vite 3.0.4

**Comment by evanw** [comment]
Yes I know. It's already fixed: adbb4753f120027a6a2152220a7d83575dfda5a9. Just waiting for tests to pass before I publish the fix. The problem was that someone else grabbed the `esbuild-linux-loong64` name before I could claim it so I needed to change the name in the contributed PR, but I missed a spot. Should be fixed in a few minutes.

**Comment by evanw** [comment]
This was fixed in [version 0.14.53](https://github.com/evanw/esbuild/releases/tag/v0.14.53) by the way.
