### ISSUE TITLE
✘ [ERROR] Could not resolve "/root/circleci-milo_vin-workingDir/npx"

### ISSUE THREAD

**Issue by milobluebell** [evanw/esbuild#2459]
### Esbuild ran failed

when `CircleCI` execute vite build.

```shell

✘ [ERROR] Could not resolve "/root/circleci-milo_vin-workingDir/npx"

failed to load config from /root/circleci-milo_vin-workingDir/npx
error during build:
Error: Build failed with 1 error:
error: Could not resolve "/root/circleci-milo_vin-workingDir/npx"
    at failureErrorWithLog (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1624:15)
    at /usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1264:7)
    at /usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1377:14
    at /usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)

Exited with code exit status 1
```

Detail: 

![image](https://user-images.githubusercontent.com/11535146/184108502-9e4f716f-7c62-4b98-bdff-3c9699f0db97.png)

### Reproduction

no

### System Info

```shell
all latest
```

### Used Package Manager

npm

### Logs

✘ [ERROR] Could not resolve "/root/circleci-milo_vin-workingDir/npx"

failed to load config from /root/circleci-milo_vin-workingDir/npx
error during build:
Error: Build failed with 1 error:
error: Could not resolve "/root/circleci-milo_vin-workingDir/npx"
    at failureErrorWithLog (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1624:15)
    at /usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1264:7)
    at /usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:1377:14
    at /usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/usr/local/lib/node_modules/vite/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)

Exited with code exit status 1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by evanw** [comment]
This is a Vite issue, not an esbuild issue. Closing.
