### ISSUE TITLE
ERROR: Invalid option in transform() call: "0"

### ISSUE THREAD

**Issue by Cyberuben** [evanw/esbuild#2500]
Hi,

I'm trying to bundle my TypeScript project using `serverless-bundle`, which in term uses `esbuild` to compile my code.

The following error seems to pop up, it took me quite a while to even get the output of this error, as bundling with multiple entrypoints caused the error to not show up at all.

```
Error:
HookWebpackError: Transform failed with 1 error:
/Users/ruben/Projects/<project>/api/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in transform() call: "0"
    at makeWebpackError (/Users/ruben/Projects/<project>/api/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/ruben/Projects/<project>/api/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/ruben/Projects/<project>/api/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
Error: Transform failed with 1 error:
/Users/ruben/Projects/<project>/api/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in transform() call: "0"
    at failureErrorWithLog (/Users/ruben/Projects/<project>/api/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/ruben/Projects/<project>/api/node_modules/esbuild/lib/main.js:1447:20
    at /Users/ruben/Projects/<project>/api/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/ruben/Projects/<project>/api/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/ruben/Projects/<project>/api/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

I can't seem to find any error related to this, other than the same error with "jsx", but that doesn't seem to have a lot of context or solutions either.

If any additional info is needed I can provide them.

**Comment by evanw** [comment]
The second argument to `transform` is supposed to be an object with properties for any API options you want to set: https://esbuild.github.io/api/#transform-api. You can get this error if you pass it something with the `0` property such as a string or an array:

```js
require('esbuild').transform('', [1, 2, 3])
```

This is not a valid use of esbuild's API, which is why esbuild's API is returning an error.

**Comment by Cyberuben** [comment]
I'm not calling esbuild myself, so I'm assuming this is either a webpack related issue or `serverless-bundle`?

If so, I'll report the issue there

**Comment by evanw** [comment]
Yes, I assume that's correct.

**Comment by evanw** [comment]
I'm going to close this because it seems like esbuild just isn't being called correctly here. We can reopen this if it turns out after examining the call site that this is somehow a problem with esbuild.
