### ISSUE TITLE
Unsupported Platform

### ISSUE THREAD

**Issue by lyonkvalid** [evanw/esbuild#2526]
` ERROR  [unhandledRejection] Unsupported platform: android arm LE

  at pkgAndSubpathForCurrentPlatform (node_modules/vite/node_modules/esbuild/lib/main.js:1768:11)
  at generateBinPath (node_modules/vite/node_modules/esbuild/lib/main.js:1803:36)                                       at esbuildCommandAndArgs (node_modules/vite/node_modules/esbuild/lib/main.js:1901:31)
  at ensureServiceIsRunning (node_modules/vite/node_modules/esbuild/lib/main.js:2065:25)                                at build (node_modules/vite/node_modules/esbuild/lib/main.js:1956:26)                                                 at runOptimizeDeps (node_modules/vite/dist/node/chunks/dep-0fc8e132.js:37202:26)                                      at processTicksAndRejections (node:internal/process/task_queues:96:5)                                               
ℹ Vite server warmed up in 2750ms                          
 ERROR  [unhandledRejection] Unsupported platform: android arm LE

  at pkgAndSubpathForCurrentPlatform (node_modules/vite/node_modules/esbuild/lib/main.js:1768:11)
  at generateBinPath (node_modules/vite/node_modules/esbuild/lib/main.js:1803:36)
  at esbuildCommandAndArgs (node_modules/vite/node_modules/esbuild/lib/main.js:1901:31)
  at ensureServiceIsRunning (node_modules/vite/node_modules/esbuild/lib/main.js:2065:25)
  at build (node_modules/vite/node_modules/esbuild/lib/main.js:1956:26)
  at runOptimizeDeps (node_modules/vite/dist/node/chunks/dep-0fc8e132.js:37202:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ERROR  (node:14622) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
(Use node --trace-warnings ... to show where the warning was created) `

I can't get VIte to work on my Android device using termux

**Comment by evanw** [comment]
This is because the Go programming language doesn't support natural cross-compilation for certain Android build targets. See #1578. I will try to have this use the WebAssembly implementation as a fallback instead. It will be much slower and may have memory usage limitations, but it will at least run.

**Comment by lyonkvalid** [comment]
Already fix it here using eebuild-wasm truly it's slow but it works anyway
