### ISSUE TITLE
Mangle CJS globals when transforming ESM to CJS

### ISSUE THREAD

**Issue by privatenumber** [evanw/esbuild#2573]
## Feature request

When transforming ESM to CJS code, variable names that collide with CJS globals like `__dirname`, `__filename`, should be mangled/renamed because it errors when running it in a CJS context.

This may be unexpected for those writing "ESM code" where creating a variable called `__dirname` is valid.

However, access to the `__dirname` global should be preserved in case they realize it runs in a CJS context and they want to reference it.

```
$ node index.js
/index.js:1
const __dirname = 'test';
      ^

SyntaxError: Identifier '__dirname' has already been declared
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

## Context
In [tsx](https://github.com/esbuild-kit/tsx), when importing a ESM package from a CJS package, if the ESM package contains `const __dirname`, it throws with the above error.

I can consider using `minifyIdentifiers`, (and I realize esbuild renames variables even without minification) but it mangles more variables to the extent of obfuscating error messages (which is not ideal even with sourcemaps -- like when using `debugger`):

```
TypeError: r is not a function
    at Object.<anonymous> (/index.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.v (/esbuild-kit/cjs-loader/dist/index.js:1:933)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at loadESM (node:internal/process/esm_loader:88:5)
```

**Comment by hyrious** [comment]
I'm not sure if esbuild knows the context of <q>transforming ESM to CJS</q>, since it only has one option `--format=cjs` and the input format is unknown (it will be guessed during parsing). One possible way is appending an `export {}` to each file to force notifying the input format.

Another possible solution is swapping these globals manually with `--define:__dirname=__injected_dirname` and prepending `const __injected_dirname = "real dirname"`, [REPL Link](https://hyrious.me/esbuild-repl/?version=0.15.8&mode=transform&input=console.log%28__dirname%29&options=--define%3A__dirname%3Dinjected_var_dirname+--banner%3D%27const+injected_var_dirname+%3D+%22works%22%3B%27). [Vite did this too](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/config.ts#L947-L949).

**Comment by privatenumber** [comment]
Good point. I think the transformation would still be safe even if we don't know if the input is ESM though.

e.g. If the input and output formats are both CJS, fixing `const __dirname`s would be safe. A minor drawback is that the original code would no longer run in Node.js, but that's easily fixable manually, and transforming code so it can run is partially what esbuild does.

Regarding your proposal using `--define`: The `const __dirname` is declared in user-code, and the CJS wrapper (`function(..., __dirname) { /* code */ }`) is added by Node.js, so I'm not sure if I can work around it using `--define`.

Alternative proposals to esbuild:
- A flag to tell it which variable names are taken and should not be used (e.g. `--declared-variables`)
- A mangle flag that accepts multiple regular expressions ([like Terser](https://github.com/terser/terser#cli-mangling-property-names---mangle-props))
