### ISSUE TITLE
No loader is configured for ".scss" files

### ISSUE THREAD

**Issue by amarg26** [evanw/esbuild#2613]
Getting error on NPM start as **No loader is configured for ".scss" files**

**package.json**

```
"scripts": {
        "prestart": "node createDb.js",
        "start": "run-p start-app start-api",
        "start-app": "vite",
        "start-api": "json-server --port 3001 --watch db.json --middlewares ./idMappings.js",
        "build1": "vite build --config vite.config.js",
        "build": "esbuild src/App.jsx --bundle --minify --sourcemap --outfile=public/bundle.jsx --loader:.js=jsx",
        "test": "jest --coverage",
        "eject": "vite eject",
        "format:check": "prettier --check \"src/**/*.js\" --check \"src/**/*.jsx\"",
        "format:fix": "prettier --write \"src/**/*.js\" --write \"src/**/*.jsx\"",
        "lint:check": "eslint src -c .eslintrc.js",
        "lint:fix": "eslint src --fix -c .eslintrc.js"
    }
"devDependencies": {
        "@rollup/plugin-alias": "^3.1.9",
        "@rushstack/eslint-patch": "^1.2.0",
        "@vitejs/plugin-react": "^2.1.0",
        "@vitejs/plugin-react-refresh": "^1.3.6",
        "babel-plugin-module-resolver": "^4.1.0",
        "esbuild": "^0.15.11",
        "eslint": "^7.32.0",
        "eslint-plugin-react-hooks": "^4.6.0",
        "jest": "^28.1.3",
        "jest-environment-jsdom": "^28.1.3",
        "jest-junit-reporter": "^1.1.0",
        "npm-run-all": "^4.1.5",
        "prettier": "^2.7.1",
        "redux-devtools-extension": "^2.13.9",
        "sass": "^1.55.0",
        "sass-loader": "^13.1.0",
        "typescript": "^3.9.10",
        "vite": "^3.1.8",
        "vite-plugin-env-compatible": "^1.1.1",
        "vite-plugin-svgr": "^2.2.2"
    },
```

**vite.config.js**

```
import fs from "fs/promises";
import { resolve } from "path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import svgrPlugin from "vite-plugin-svgr";
import envCompatible from "vite-plugin-env-compatible";

require("esbuild").buildSync({
    entryPoints: ["./src/components/app.jsx"],
    bundle: true,
    loader: { ".js": "jsx" },
    outfile: "out.js",
    external: ["*.png", "./src/images/*"],
});

const projectRootDir = resolve(__dirname);

export default () => {
    return defineConfig({
        server: {
            open: true,
        },
        esbuild: {
            include: /\.(tsx?|jsx?)$/,
            exclude: [],
        },
        css: {
            preprocessorOptions: {
                scss: {
                    additionalData: `
                    @import "/src/components/app-cdn.scss";
                    @import "/src/components/customScss.scss";
                    @import "/src/components/form8862CTCEntry/grid.scss";
                    @import "/src/components/f8396/f8396/f8396.scss";
                    @import "/src/components/mainMenuList/menuList.scss";
                    @import "/src/components/form8862/f8862EIC.scss";
                    @import "/src/components/scheduleR/Statement/statement.scss";
                `,
                },
            },
        },
        resolve: {
            extensions: [
                ".mjs",
                ".js",
                ".ts",
                ".jsx",
                ".tsx",
                ".json",
                ".scss",
            ],
            alias: [
                {
                    find: "@",
                    replacement: resolve(projectRootDir, "src"),
                },
                {
                    find: "@components",
                    replacement: resolve(projectRootDir, "./src/components"),
                },
                {
                    find: "@config",
                    replacement: resolve(projectRootDir, "./src/config"),
                },
            ],
        },
        envPrefix: "REACT_APP_",
        optimizeDeps: {
            esbuildOptions: {
                plugins: [
                    {
                        name: "load-js-files-as-jsx",
                        setup(build) {
                            build.onLoad(
                                { filter: /src\/.*\.jsx$/ },
                                async (args) => ({
                                    loader: { ".js": "jsx" },
                                    contents: await fs.readFile(
                                        args.path,
                                        "utf8"
                                    ),
                                })
                            );
                        },
                    },
                ],
            },
        },
        plugins: [
            react(),
            envCompatible,
            svgrPlugin({
                svgrOptions: {
                    icon: true,
                },
            }),
        ],
    });
};
```

**Error Log**

```
failed to load config from D:\xyz\vite.config.js
error when starting dev server:
Error: Build failed with 9 errors:
src/components/app.jsx:15:7: ERROR: No loader is configured for ".scss" files: src/components/app.scss
src/components/app.jsx:16:7: ERROR: No loader is configured for ".scss" files: src/components/customScss.scss  
src/components/app.jsx:122:12: ERROR: No loader is configured for ".scss" files: src/components/app-cdn.scss   
src/components/f8396/f8396/form.jsx:10:7: ERROR: No loader is configured for ".scss" files: src/components/f8396/f8396/f8396.scss
src/components/f8396/helpInfo/form.jsx:4:7: ERROR: No loader is configured for ".scss" files: src/components/f8396/helpInfo/helpInfo.scss
...
    at failureErrorWithLog (D:\xyz\node_modules\esbuild\lib\main.js:1566:15)
    at D:\xyz\node_modules\esbuild\lib\main.js:1024:28
    at D:\xyz\node_modules\esbuild\lib\main.js:969:67
    at buildResponseToResult (D:\xyz\node_modules\esbuild\lib\main.js:1022:7)
    at D:\xyz\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (D:\xyz\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (D:\xyz\src\node_modules\esbuild\lib\main.js:726:9)
  run `npm fund` for details

```

**Comment by evanw** [comment]
This is expected. SCSS is not a file type that esbuild supports: https://esbuild.github.io/content-types/. You could potentially get SCSS to work with esbuild using an esbuild plugin. 

However, it looks like you are using Vite, which does support SCSS. You should file an issue with Vite if you are having trouble with Vite instead of filing one here. This is not the correct repo for Vite support requests. 

Closing this issue as invalid.
