### ISSUE TITLE
Error: You installed esbuild on another platform than the one you're currently using

### ISSUE THREAD

**Issue by robyhuzwandar** [evanw/esbuild#2617]
What is the meaning of this Error message?

```
$ doppler run -c dev -- run-p 'dev:*' -- --watch
$ cross-env NODE_ENV=development node --inspect --require ./node_modules/dotenv/config --require ./mocks ./build/server.js
$ cross-env NODE_ENV=development yarn run build:server --watch
$ cross-env NODE_ENV=development yarn run generate:css --watch
$ cross-env NODE_ENV=development remix watch
Debugger listening on ws://127.0.0.1:9229/d29xxx
For help, see: https://nodejs.org/en/docs/inspector
$ esbuild --platform=node --format=cjs ./server.ts --outdir=build --watch
$ tailwindcss -o ./app/styles/tailwind.css --watch
🔶 Mock server running
..<my directory>../node_modules/esbuild/bin/esbuild:107
          throw new Error(`
          ^
Error: 
You installed esbuild on another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "esbuild-darwin-arm64" package is present but this platform
needs the "esbuild-darwin-64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

If you are installing with npm, you can try not copying the "node_modules"
directory when you copy the files over, and running "npm ci" or "npm install"
on the destination platform after the copy. Or you could consider using yarn
instead which has built-in support for installing a package on multiple
platforms simultaneously.

If you are installing with yarn, you can try listing both this platform and the
other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.
    at generateBinPath (..<my directory>../node_modules/esbuild/bin/esbuild:107:17)
    at Object.<anonymous> (..<my directory>../node_modules/esbuild/bin/esbuild:163:39)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
```

**Comment by eriksavage** [comment]
I'm using `./node_modules/.bin/esbuild --version 0.15.10` on the redwoodjs tutorial. 
OS: macOS Monterey v12.6, M1 chip

If I try to run my server though the macOS terminal everything builds fine. But if I try to use the zsh terminal embedded in VScode I am getting the below error telling me I should be using the "esbuild-darwin-64" package instead. Same thing happens if I try to check the version, works fine in macOS terminal but get the error again in VScode terminal.

Let me know if there are any additional details that could be provided to help.

```
yarn rw dev
gen | Generating TypeScript definitions and GraphQL schemas...
gen | 35 files generated
api | Error: 
api | You installed esbuild for another platform than the one you're currently using.
api | This won't work because esbuild is written with native code and needs to
api | install a platform-specific binary executable.
api | 
api | Specifically the "esbuild-darwin-arm64" package is present but this platform
api | needs the "esbuild-darwin-64" package instead. People often get into this
api | situation by installing esbuild with npm running inside of Rosetta 2 and then
api | trying to use it with node running outside of Rosetta 2, or vice versa (Rosetta
api | 2 is Apple's on-the-fly x86_64-to-arm64 translation service).
api | 
api | If you are installing with npm, you can try ensuring that both npm and node are
api | not running under Rosetta 2 and then reinstalling esbuild. This likely involves
api | changing how you installed npm and/or node. For example, installing node with
api | the universal installer here should work: https://nodejs.org/en/download/. Or
api | you could consider using yarn instead of npm which has built-in support for
api | installing a package on multiple platforms simultaneously.
api | 
api | If you are installing with yarn, you can try listing both "arm64" and "x64"
api | in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
api | https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
api | Keep in mind that this means multiple copies of esbuild will be present.
api | 
api | Another alternative is to use the "esbuild-wasm" package instead, which works
api | the same way on all platforms. But it comes with a heavy performance cost and
api | can sometimes be 10x slower than the "esbuild" package, so you may also not
api | want to do that.
api | 
api |     at generateBinPath (/Users/erik/projects/courses/redwood-tutorial/redwoodblog/node_modules/esbuild/lib/main.js:1799:17)
api |     at esbuildCommandAndArgs (/Users/erik/projects/courses/redwood-tutorial/redwoodblog/node_modules/esbuild/lib/main.js:1875:33)
api |     at ensureServiceIsRunning (/Users/erik/projects/courses/redwood-tutorial/redwoodblog/node_modules/esbuild/lib/main.js:2040:25)
api |     at startSyncServiceWorker (/Users/erik/projects/courses/redwood-tutorial/redwoodblog/node_modules/esbuild/lib/main.js:2250:19)
api |     at Object.<anonymous> (/Users/erik/projects/courses/redwood-tutorial/redwoodblog/node_modules/esbuild/lib/main.js:2291:3)
api |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
api |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
api |     at Module.load (internal/modules/cjs/loader.js:950:32)
api |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
api |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
```

VScode details if helpful:
```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0
```

**Comment by evanw** [comment]
> If I try to run my server though the macOS terminal everything builds fine. But if I try to use the zsh terminal embedded in VScode I am getting the below error telling me I should be using the "esbuild-darwin-64" package instead. Same thing happens if I try to check the version, works fine in macOS terminal but get the error again in VScode terminal.

It looks like you are installing with yarn. Did you see this part of the message?

```
If you are installing with yarn, you can try listing both "arm64" and "x64"
in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.
```

**Comment by eriksavage** [comment]
> It looks like you are installing with yarn. Did you see this part of the message?
> 
> ```
> If you are installing with yarn, you can try listing both "arm64" and "x64"
> in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
> https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
> Keep in mind that this means multiple copies of esbuild will be present.
> ```

I did read that part of the message, just didn't realize that what was impacting me. Ended up tinkering with the config file as you suggested, but ultimately I just need to do `yarn install` if I switch the location I'm going to be running the server. Thanks for the help and sorry for the false alarm!

**Comment by evanw** [comment]
Ok, makes sense. I'm going to close this issue as the instructions in the error message appear to be accurate.

**Comment by PedroRafael13** [comment]
Where would I need to go for information about error ?

**Comment by PedroRafael13** [comment]
There's no other way ? you talked about Yarn and about npm ?
