### ISSUE TITLE
Building lit-virtualizer fails

### ISSUE THREAD

**Issue by trading-peter** [evanw/esbuild#264]
Hi,

I'm unable to build my project that uses [lit-virtualizer](https://github.com/PolymerLabs/uni-virtualizer/tree/master/packages/lit-virtualizer). First up I created a minimal example repo to demonstrate this problem. It has a readme with the steps to reproduce the following errors. https://github.com/trading-peter/esbuild_edge

On the first run of the build script it errors out with this:

```
Error: Build failed with 3 errors:
error: Cannot traverse from chunk "../node_modules/lit-virtualizer/lib/uni-virtualizer/lib/layouts/Layout1d.js" to chunk "chunk.m6OIDGXX.js"
error: Refusing to overwrite input file: node_modules/lit-virtualizer/lib/uni-virtualizer/lib/layouts/Layout1d.js
error: Refusing to overwrite input file: node_modules/resize-observer-polyfill/dist/ResizeObserver.es.js
    at failureErrorWithLog (/home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:407:15)
    at /home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:373:29
    at handleIncomingPacket (/home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:357:9)
    at Socket.readFromStdout (/home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:305:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:505:15)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

and after that if running the script again with this error:

```
Error: Build failed with 1 error:
node_modules/lit-virtualizer/lib/uni-virtualizer/lib/layouts/Layout1d.js:1:14: error: Could not resolve ""
    at failureErrorWithLog (/home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:407:15)
    at /home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:373:29
    at handleIncomingPacket (/home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:357:9)
    at Socket.readFromStdout (/home/pk/Dokumente/esbuild_edge/litvirtualizer/node_modules/esbuild/lib/main.js:305:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:505:15)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

The build script in the uses gulp and looks like this:

```js
const gulp = require('gulp');

const esBuildClient = async () => {
  const { build } = require('esbuild');

  return build({
    entryPoints: [
      'entrypoints/entry1.js',
      'entrypoints/entry2.js',
    ],
    outdir: 'dist',
    minify: true,
    bundle: true,
    sourcemap: true,
    splitting: true,
    format: 'esm'
  })
};

gulp.task('esbuild', async () => {
  await esBuildClient()
});
```

In my real app I need the `splitting` option, that's why its also set in the example. Could ofc also be that I'm doing something wrong :smile:

**Comment by chowey** [comment]
I got a similar error `error: Cannot traverse from chunk ...`.

I had a dynamic import that was shared between two entry points, although I haven't been able to reproduce it in a small example yet. I do know that when I removed the dynamic import, the error went away.
