### ISSUE TITLE
npm package fails to install when you don't have yarn installed

### ISSUE THREAD

**Issue by evmar** [evanw/esbuild#274]
I have a `node` binary but no `npm` binary, and the postinstall (?) of the esbuild module consequently fails.

In case it's relevant this is on a WSL system that is running Alpine Linux.

```
$ yarn add -D esbuild
yarn add v1.19.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/evmar/smash/web/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/evmar/smash/web/node_modules/esbuild
Output:
/bin/sh: npm: not found
child_process.js:660
    throw err;
    ^

Error: Command failed: npm install --silent --prefer-offline --no-audit --progress=false esbuild-linux-64@0.6.3
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at installBinaryFromPackage (/home/evmar/smash/web/node_modules/esbuild/install.js:33:17)
    at installOnUnix (/home/evmar/smash/web/node_modules/esbuild/install.js:71:5)
    at Object.<anonymous> (/home/evmar/smash/web/node_modules/esbuild/install.js:117:5)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 7350,
  stdout: null,
  stderr: null
}
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by evmar** [comment]
I apologize in advance because I know the sort of hassle bugs like this can be (fiddling with npm is not your goal in esbuild).

A workaround for now is `yarn add -D esbuild-linux-64` because I am unlikely to touch this project on a non-Linux system.
