### ISSUE TITLE
Issue with `pkg` and `esbuild`

### ISSUE THREAD

**Issue by WorriedArrow** [evanw/esbuild#2788]
I am using vercel's pkg to create executables for my application. esbuild is working like normal when I run it with `node .` however when I run the executable after packaging, I get the following error:
```
C:\Users\<username>\AppData\Roaming\discord\settings.json
C:\snapshot\OpenLoader\node_modules\esbuild\lib\main.js:2248
      throw reject;
      ^

Error: The package "@esbuild/win32-x64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.
    at generateBinPath (C:\snapshot\OpenLoader\node_modules\esbuild\lib\main.js:1840:15)
    at esbuildCommandAndArgs (C:\snapshot\OpenLoader\node_modules\esbuild\lib\main.js:1907:33)
    at ensureServiceIsRunning (C:\snapshot\OpenLoader\node_modules\esbuild\lib\main.js:2072:25)
    at startSyncServiceWorker (C:\snapshot\OpenLoader\node_modules\esbuild\lib\main.js:2282:19)
    at Object.<anonymous> (C:\snapshot\OpenLoader\node_modules\esbuild\lib\main.js:2323:3)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
```

Here is my package.json:
```json
{
  "name": "openloader",
  "version": "0.2.0",
  "description": "A plugin loader for Discord made possible by OpenAsar.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "bin": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "pkg": {
    "assets": "src/**/*",
    "targets": [
      "linux-node14",
      "win-node14",
      "mac-node14"
    ],
    "outputPath": "installer"
  },
  "dependencies": {
    "esbuild": "^0.16.10"
  }
}
```

I would like the correct platform's esbuild binary to be bundled with the right executable. Is there a way to do this?

**Comment by evanw** [comment]
I'm not familiar with the tool you're using. But shouldn't this bug report be directed toward that tool instead of esbuild? It sounds like esbuild's node package is working correctly with node. If some tool you're using is supposed to package node-based programs but it's not doing that correctly, then isn't that a problem with that tool instead of with esbuild?

**Comment by WorriedArrow** [comment]
Yes, I apologize for that.
Sorry about the confusion!
