### ISSUE TITLE
cjs dynamic import files not be bundled

### ISSUE THREAD

**Issue by wangchuan95** [evanw/esbuild#2923]
There is a entry file:

```javascript
// src/index.js

function translate(lang, key) {
  var data = require('./i18n/' + lang + '.js');
  console.log(key, '=>', data[key]);
}

translate('zh', 'hello');
```

If I run:

```bash
node src/index.js
```

it output:

```output
hello => 你好
```

But if I bundle it:

```bash
pnpm build
```

Then I run:

```bash
node dist/index.js
```

it output:

```output
node:internal/modules/cjs/loader:1050
  throw err;
  ^

Error: Cannot find module './i18n/zh.js'
Require stack:
- D:\test\esbuild-test\dist\index.js
?[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)?[39m
?[90m    at Module._load (node:internal/modules/cjs/loader:893:27)?[39m
?[90m    at Module.require (node:internal/modules/cjs/loader:1113:19)?[39m
?[90m    at require (node:internal/modules/cjs/helpers:103:18)?[39m
    at translate ?[90m(D:\test\esbuild-test\?[39mdist\index.js:12:16?[90m)?[39m
    at ?[90mD:\test\esbuild-test\?[39mdist\index.js:15:3
    at Object.<anonymous> ?[90m(D:\test\esbuild-test\?[39mdist\index.js:16:3?[90m)?[39m
?[90m    at Module._compile (node:internal/modules/cjs/loader:1226:14)?[39m
?[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)?[39m
?[90m    at Module.load (node:internal/modules/cjs/loader:1089:32)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [ ?[32m'D:\\test\\esbuild-test\\dist\\index.js'?[39m ]
}

Node.js v18.14.0
```

There are my other files:

package.json:

```json
{
  "name": "esbuild-test",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "build": "node ./build.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "esbuild": "^0.17.8"
  }
}
```

```javascript
// build.js

require('esbuild')
  .build({
    entryPoints: ['src/index.js'],
    bundle: true,
    outdir: 'dist',
  })
  .catch(() => process.exit(1));
```

```javascript
// src/i18n/zh.js

module.exports = {
  hello: '你好',
};
```

```javascript
// src/i18n/en.js

module.exports = {
  hello: 'hello',
};
```

**Comment by hyrious** [comment]
This is already documented here: [Non-analyzable imports](https://esbuild.github.io/api/#non-analyzable-imports)

You can edit your code to something like this:

```js
// src/index.js
const translates = {
  en: require('./i18n/en.js'),
  zh: require('./i18n/zh.js'),
}
function translate(lang, key) {
  var data = translates[lang]
  console.log(key, '=>', data[key])
}
```

**Comment by wangchuan95** [comment]
> This is already documented here: [Non-analyzable imports](https://esbuild.github.io/api/#non-analyzable-imports)

Thanks a lot!
