### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL - when running a bundle that includes tiny-secp256k1

### ISSUE THREAD

**Issue by meglio** [evanw/esbuild#3039]
I'm building for node environment and using `tiny-secp256k1` package.

The build is successful, but when running, an error is thrown:

```
node:internal/url:565
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:393:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at path (/Users/.../.../.../esbuildtest/bin/jstools.js:19452:15)
    at Object.<anonymous> (/Users/.../.../.../esbuildtest/bin/jstools.js:19467:42)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  input: 'secp256k1.wasm',
  code: 'ERR_INVALID_URL'
}
```

Here is that piece in the file with line `19452`:

```js
// node_modules/tiny-secp256k1/lib/wasm_path.js
var import_url = require("url");
var import_meta = {};
function path(wasmFilename) {
  const url = new import_url.URL(wasmFilename, import_meta.url);  // <- line 19452
  return (0, import_url.fileURLToPath)(url);
}
```

Am I doing it wrong, or is it a bug?

**Comment by hyrious** [comment]
This is because `import.meta.url` is not supported in your context (CJS or IIFE), it is only supported in ESM. So esbuild transforms that to `var import_meta = {}`.

Since your runtime is Node.js, you can do either:

- Mark tiny-secp256k1 as external `--external:tiny-secp256k1`.
- Set output format to esm `--format=esm`, you may also need to set out extension to .mjs for Node.js to know the context.
- Add a plugin to transform `import.meta.url` to the real absolute path in your FS. You can take a look at [how tsup did it](https://github.com/egoist/tsup/blob/-/assets/cjs_shims.js).

**Comment by meglio** [comment]
So, if I go with the esm format, will it literally bundle the source wasm file in the bundle and make it automagically work?

**Comment by meglio** [comment]
I tried `--format=esm`. Building successful, but error when running:

```
file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:13
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "buffer" is not supported
    at file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:13:9
    at node_modules/bitcoinjs-lib/src/types.js (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:6419:20)
    at __require2 (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:16:51)
    at node_modules/bitcoinjs-lib/src/script_signature.js (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:6531:17)
    at __require2 (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:16:51)
    at node_modules/bitcoinjs-lib/src/script.js (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:6602:27)
    at __require2 (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:16:51)
    at node_modules/bitcoinjs-lib/src/payments/embed.js (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:6809:19)
    at __require2 (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:16:51)
    at node_modules/bitcoinjs-lib/src/payments/index.js (file:///Users/.../.../.../esbuildtest/bin/jstools.mjs:12372:19)

Node.js v18.12.1
```

**Comment by hyrious** [comment]
> Dynamic require of "buffer" is not supported

That's another issue, that cjs code will be wrapped in a callback in esm bundle result in esbuild, and Node.js forbids any dynamic require on builtin modules. More details see #1921.

The best solution to this (not workarounds) IMO is to ensure all dependencies of your bundle are in ESM format. You can enable [metafile](https://esbuild.github.io/api/#metafile) and use the official [analyzer](https://esbuild.github.io/analyze/) to check it.

> will it literally bundle the source wasm file into the bundle and make it automagically work?

To bundle a wasm file, first of all it has to be imported into the code with direct imports (`import wasmBinary from './file.wasm'`). Then you could make use of [the wasm plugin](https://esbuild.github.io/plugins/#webassembly-plugin) to do so.

**Comment by meglio** [comment]
Okay, since I don't control how the packages use .wasm files, nor whether they are available in the ESM format, turns out this option is not viable.

Next, I should try `--external:tiny-secp256k1`. If I make it external, does it mean I'll have to `npm i tiny-secp256k1` in the project's directory before I can call the bundled file? Or is there a better way? I'm trying to avoid installing packages with using npm, being my ultimate goal for using esbuild.

**Comment by hyrious** [comment]
Since your main purpose is creating a bundle.js with everything bundled in, it is not that hard to go with the wasm plugin approach. Let me give you a tiny example: https://gist.github.com/hyrious/311a8d7af354e94ab64a70a4da757e49

**Comment by evanw** [comment]
I'm closing this issue because this is not a problem with esbuild.
