### ISSUE TITLE
0.17.15 adds unused `__esbuild_register_import_meta_url__`

### ISSUE THREAD

**Issue by unindented** [evanw/esbuild#3040]
When upgrading from `0.17.14` to `0.17.15`, I've started encountering this error when trying to build my instance of Storybook 7.0.2.

It seems like `esbuild` has started generating unused `meta_url` variables, and then `ts-node` fails because it's running in `strict` mode.

```
ERR! TSError: ⨯ Unable to compile TypeScript:
ERR! ../../packages/ui/postcss.config.js:1:7 - error TS6133: '__esbuild_register_import_meta_url__' is declared but its value is never read.
ERR!
ERR! 1 const __esbuild_register_import_meta_url__ = require('url').pathToFileURL(__filename).href;
ERR!         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERR!
ERR!     at createTSError (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.3/node_modules/ts-node/dist/index.js:255:12)
ERR!     at reportTSError (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.3/node_modules/ts-node/dist/index.js:258:19)
ERR!     at getOutput (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.3/node_modules/ts-node/dist/index.js:387:11)
ERR!     at Object.compile (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.3/node_modules/ts-node/src/index.ts:1244:28)
ERR!     at Module.m._compile (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.3/node_modules/ts-node/src/index.ts:1390:9)
ERR!     at Module._compile (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/esbuild-register@3.4.2_esbuild@0.17.15/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
ERR!     at newLoader (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/esbuild-register@3.4.2_esbuild@0.17.15/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at extensions..js (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/esbuild-register@3.4.2_esbuild@0.17.15/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Object.require.extensions.<computed> [as .js] (/Volumes/Stuff/Code/myopic-design/nextjs-tailwindcss-template/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.15.11_typescript@5.0.3/node_modules/ts-node/src/index.ts:1394:5)
ERR! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ERR! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ERR! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ERR! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by evanw** [comment]
That's not something that esbuild does. Closing this issue as invalid.

I assume that you meant to post this issue to https://github.com/egoist/esbuild-register instead. Specifically the symbol you mention comes from here: https://github.com/egoist/esbuild-register/blob/4184f944da7bd6a654389c08e46be6d555da326b/src/node.ts#L15.
