### ISSUE TITLE
Command failed when using yarn

### ISSUE THREAD

**Issue by jjaramillom** [evanw/esbuild#3050]
I'm working on a project using Vue and Vite. Somehow today I checked a branch to review it, and when I ran `yarn` to install the new dependencies something broke.
Everything was working fine, but now I have no idea what went wrong. 

I'm using node 16.17.1 via nvm. I also tried using a latest node version but the error remains.

``` 
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @graphql-codegen/typescript-vue-apollo@3.2.10" has unmet peer dependency "graphql-tag@^2.0.0".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > @vitejs/plugin-vue@4.1.0" has incorrect peer dependency "vue@^3.2.25".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/actions@1.10.2" has unmet peer dependency "@interactjs/core@1.10.2".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/actions@1.10.2" has unmet peer dependency "@interactjs/utils@1.10.2".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/auto-scroll@1.10.2" has unmet peer dependency "@interactjs/utils@1.10.2".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/auto-start@1.10.2" has unmet peer dependency "@interactjs/core@1.10.2".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/auto-start@1.10.2" has unmet peer dependency "@interactjs/utils@1.10.2".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/modifiers@1.10.2" has unmet peer dependency "@interactjs/core@1.10.2".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/modifiers@1.10.2" has unmet peer dependency "@interactjs/utils@1.10.2".
warning "workspace-aggregator-25081ac5-713d-4645-8d86-f479010c52cf > ms-ui > vue-grid-layout > @interactjs/modifiers > @interactjs/snappers@1.10.2" has unmet peer dependency "@interactjs/utils@1.10.2".
[5/5] Building fresh packages...
[6/7] ⡀ @apollo/protobufjs
[2/7] ⡀ esbuild
[3/7] ⡀ full-icu
[-/7] ⡀ waiting...
error /home/jacobo/dev/DI/microservices/frontend/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/jacobo/dev/DI/microservices/frontend/node_modules/esbuild
Output:
node:internal/errors:856
  const err = new Error(message);
              ^

Error: Command failed: /home/jacobo/.nvm/versions/node/v16.17.1/bin/node /home/jacobo/dev/DI/microservices/frontend/node_modules/esbuild/bin/esbuild --version
node:child_process:879
    throw err;
    ^

Error: Command failed: /home/jacobo/dev/DI/microservices/frontend/node_modules/@esbuild/linux-x64/bin/esbuild --version
    at checkExecSyncError (node:child_process:841:11)
    at Object.execFileSync (node:child_process:876:15)
    at Object.<anonymous> (/home/jacobo/dev/DI/microservices/frontend/node_modules/esbuild/bin/esbuild:220:28)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: null,
  signal: 'SIGSEGV',
  output: [ null, null, null ],
  pid: 15717,
  stdout: null,
  stderr: null
}

    at checkExecSyncError (node:child_process:841:11)
    at Object.execFileSync (node:child_process:876:15)
    at validateBinaryVersion (/home/jacobo/dev/DI/microservices/frontend/node_modules/esbuild/install.js:98:28)
    at /home/jacobo/dev/DI/microservices/frontend/node_modules/esbuild/install.js:283:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(920) [Uint8Array] [
      110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
      114, 111,  99, 101, 115, 115,  58,  56,  55,  57,  10,  32,
       32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114, 114,
       59,  10,  32,  32,  32,  32,  94,  10,  10,  69, 114, 114,
      111, 114,  58,  32,  67, 111, 109, 109,  97, 110, 100,  32,
      102,  97, 105, 108, 101, 100,  58,  32,  47, 104, 111, 109,
      101,  47, 106,  97,  99, 111,  98, 111,  47, 100, 101, 118,
       47,  68,  73,  47, 109, 105,  99, 114, 111, 115, 101, 114,
      118, 105,  99, 101,
      ... 820 more items
    ]
  ],
  pid: 15709,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(920) [Uint8Array] [
    110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
    114, 111,  99, 101, 115, 115,  58,  56,  55,  57,  10,  32,
     32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114, 114,
     59,  10,  32,  32,  32,  32,  94,  10,  10,  69, 114, 114,
    111, 114,  58,  32,  67, 111, 109, 109,  97, 110, 100,  32,
    102,  97, 105, 108, 101, 100,  58,  32,  47, 104, 111, 109,
    101,  47, 106,  97,  99, 111,  98, 111,  47, 100, 101, 118,
     47,  68,  73,  47, 109, 105,  99, 114, 111, 115, 101, 114,
    118, 105,  99, 101,
```

**Comment by Inqnuam** [comment]
Not sure this is esbuild related issue.
Have you tried `yarn install --force` ?

**Comment by evanw** [comment]
> signal: 'SIGSEGV',

This is the problem. You'll need to debug why esbuild is segfaulting on your computer. That's not something that I'll be able to debug on my end, sorry. 

In case it helps: The only issue that anyone has filed with esbuild that looks similar is this one: #1572. They debugged the issue themselves and were able to determine an appropriate fix.

**Comment by jjaramillom** [comment]
> 

Unfortunately it didn't work.

**Comment by jjaramillom** [comment]
> Not sure this is esbuild related issue. Have you tried `yarn install --force` ?

Unfortunately it didn't work.

**Comment by evanw** [comment]
I marked this issue as `unactionable` because there's nothing I can do with this report.

**Comment by evanw** [comment]
I'm closing this issue because it has been unactionable for a while and no additional information was provided.

**Comment by 2colours** [comment]
> This is the problem. You'll need to debug why esbuild is segfaulting on your computer. That's not something that I'll be able to debug on my end, sorry.

@evanw debug how, though? I'm getting the same error, nvm installation, too, completely unrelated project and npm as the package manager. Not sure why esbuild is even needed for a goddamn Discord bot, to be honest.

**Comment by prisis** [comment]
> > This is the problem. You'll need to debug why esbuild is segfaulting on your computer. That's not something that I'll be able to debug on my end, sorry.
> 
> @evanw debug how, though? I'm getting the same error, nvm installation, too, completely unrelated project and npm as the package manager. Not sure why esbuild is even needed for a goddamn Discord bot, to be honest.
> 
> For what it's worth, even `node_modules/esbuild/bin/esbuild --version` produces this error so it's probably debuggable, I just never anticipated having to deal with something like this for merely installing my Discord bot on a different environment.

Maybe you check your dependencies, you using tsx, tsx is using esbuild, just a tip ;)

**Comment by 2colours** [comment]
> Maybe you check your dependencies, you using tsx, tsx is using esbuild, just a tip ;)

It's probably tsx, then. Now I could roll it forward and ask why tsx depends on esbuild when it runs on the backend... but there is no point. It would be useful to get somewhere with the issue itself. 

Not sure if we ever got to know the environment used by the OP. Now I rather suspect it's system related. The `nvm`-based environment is fine on Debian 12 but explodes violently on Mageia 9. What should I run to gather further info about the failure?
