### ISSUE TITLE
esbuild killed immediately with SIGKILL

### ISSUE THREAD

**Issue by benasher44** [evanw/esbuild#3097]
Heads up that some endpoint security we have has flagged esbuild as OSX.MacStealer, so invoking it results in an immediate SIGKILL

```sh
./node_modules/@esbuild/darwin-arm64/bin/esbuild --version
[1]    85163 killed     ./node_modules/@esbuild/darwin-arm64/bin/esbuild --version
```

**Comment by benasher44** [comment]
yarn users might get a log like this upon trying to install it:
```
# This file contains the result of Yarn building a package (esbuild@npm:0.17.18)
# Script name: postinstall

node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: /Users/basher/.nvm/versions/node/v18.16.0/bin/node PATH_TO_APP/node_modules/esbuild/bin/esbuild --version
node:child_process:924
    throw err;
    ^

Error: Command failed: PATH_TO_APP/node_modules/@esbuild/darwin-arm64/bin/esbuild --version
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Object.<anonymous> (PATH_TO_APP/node_modules/esbuild/bin/esbuild:220:28)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  status: null,
  signal: 'SIGKILL',
  output: [ null, null, null ],
  pid: 85197,
  stdout: null,
  stderr: null
}

Node.js v18.16.0

    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at validateBinaryVersion (PATH_TO_APP/node_modules/esbuild/install.js:98:28)
    at PATH_TO_APP/node_modules/esbuild/install.js:283:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(925) [Uint8Array] [
      110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
      114, 111,  99, 101, 115, 115,  58,  57,  50,  52,  10,  32,
       32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114, 114,
       59,  10,  32,  32,  32,  32,  94,  10,  10,  69, 114, 114,
      111, 114,  58,  32,  67, 111, 109, 109,  97, 110, 100,  32,
      102,  97, 105, 108, 101, 100,  58,  32,  47,  85, 115, 101,
      114, 115,  47,  98,  97, 115, 104, 101, 114,  47,  99, 111,
      100, 101,  47,  97, 115, 104,  98, 121,  47, 102, 114, 111,
      110, 116, 101, 110,
      ... 825 more items
    ]
  ],
  pid: 85196,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(925) [Uint8Array] [
    110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
    114, 111,  99, 101, 115, 115,  58,  57,  50,  52,  10,  32,
     32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114, 114,
     59,  10,  32,  32,  32,  32,  94,  10,  10,  69, 114, 114,
    111, 114,  58,  32,  67, 111, 109, 109,  97, 110, 100,  32,
    102,  97, 105, 108, 101, 100,  58,  32,  47,  85, 115, 101,
    114, 115,  47,  98,  97, 115, 104, 101, 114,  47,  99, 111,
    100, 101,  47,  97, 115, 104,  98, 121,  47, 102, 114, 111,
    110, 116, 101, 110,
    ... 825 more items
  ]
}

Node.js v18.16.0

```

**Comment by benasher44** [comment]
Going to close this since it's not esbuild's problem (I don't think), but now there is an issue here for those who were initially as confused as I was

**Comment by benasher44** [comment]
FWIW, installing newer versions doesn't seem to help

**Comment by benasher44** [comment]
Also if you want to see if this is the same issue on your machine, open Console.app, search for esbuild, and start streaming logs. Run the command and see what the logs say about esbuilt. It should call out whether it was killed for a security reason

**Comment by AndrewDryga** [comment]
Do you know if anyone has found a way to resolve this? I'm hitting the same issue too on pretty much any esbuild version except 0.14.41:
```
❯ /Users/andrew/Projects/os/firezone/elixir/_build/esbuild-darwin-arm64 -h     
[1]    94776 killed     /Users/andrew/Projects/os/firezone/elixir/_build/esbuild-darwin-arm64 -h
```

**Comment by AndrewDryga** [comment]
See #2512
