### ISSUE TITLE
please i need help on this

### ISSUE THREAD

**Issue by Nedum100** [evanw/esbuild#3106]
The service is no longer running
    at C:\Users\Dell technology\my-app\node_modules\esbuild\lib\main.js:1073:25
    at sendRequest (C:\Users\Dell technology\my-app\node_modules\esbuild\lib\main.js:693:14)
    at buildOrContextContinue (C:\Users\Dell technology\my-app\node_modules\esbuild\lib\main.js:1071:5)
    at C:\Users\Dell technology\my-app\node_modules\esbuild\lib\main.js:983:11

**Comment by evanw** [comment]
This issue does not contain enough information. Marking as `unactionable` as there is nothing that can be done with it.

**Comment by evanw** [comment]
Closing as there was no reply.
