### ISSUE TITLE
Can't dynamically import files that have a * star in the filename

### ISSUE THREAD

**Issue by slalomzacharyd** [evanw/esbuild#3330]
It seems that dynamic imports where any of the file paths contain a `*` fails.  Static imports work.

```
import('src/pages/*');  // fails
```

```
import('src/pages/*/index.tsx') // fails
```

```
import m from 'src/pages/*'; // works
```

It sounds like there is a recent feature for glob dynamic imports.  There doesn't seem to be any documentation or any way to opt out of it.

```
✘ [ERROR] Could not resolve "src/pages/*"

    src/entry.tsx:13:7:
      13 │ import('src/pages/*');
         ╵        ~~~~~~~~~~~~~~~

  You can mark the path "src/pages/*" as external to exclude it from the bundle, which will remove
  this error. You can also add ".catch()" here to handle this failure at run-time instead of
  bundle-time.

/Development/corgi-react-frontend-accelerator/node_modules/esbuild/lib/main.js:1649
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
src/entry.tsx:13:7: ERROR: Could not resolve "src/pages/*"
    at failureErrorWithLog (/Development/corgi-react-frontend-accelerator/node_modules/esbuild/lib/main.js:1649:15)
    at /Development/corgi-react-frontend-accelerator/node_modules/esbuild/lib/main.js:1058:25
    at /Development/corgi-react-frontend-accelerator/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

**Comment by slalomzacharyd** [comment]
Using this approach seems to avoid the problem:

```
const glob = '*';
import(`src/pages/${glob}`);
```

**Comment by slalomzacharyd** [comment]
Though it look slike 
```
import('src/pages/${glob}/something')
```
is still a problem

**Comment by mohamedmansour** [comment]
Duplicate #3320

**Comment by slalomzacharyd** [comment]
I don't know how I missed that issue.  Thank you
