### ISSUE TITLE
ReferenceError: __name is not defined

### ISSUE THREAD

**Issue by zszhengshang** [evanw/esbuild#3455]
I have an issue. I'm using esbuild with through rollup.

- Rollup Version: 2.75.7
- esbuild Version: 0.19.5

```
import { rollup } from 'rollup'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import VueMacros from 'unplugin-vue-macros/rollup'
import { nodeResolve } from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import esbuild from 'rollup-plugin-esbuild'
import glob from 'fast-glob'
import { excludeFiles, pkgRoot, suRoot, writeBundles } from '../utils'
import { buildConfigEntries } from '../build-info'
import type { OutputOptions } from 'rollup'

export const buildModules = async () => {
  const input = excludeFiles(
    await glob('**/*.{js,ts,vue}', {
      cwd: pkgRoot,
      absolute: true,
      onlyFiles: true,
    })
  )
  const bundle = await rollup({
    input,
    plugins: [
      VueMacros({
        setupComponent: false,
        setupSFC: false,
        plugins: {
          vue: vue({
            isProduction: false,
          }),
          vueJsx: vueJsx(),
        },
      }),
      nodeResolve({
        extensions: ['.mjs', '.js', '.json', '.ts'],
      }),
      commonjs(),
      esbuild({
        sourceMap: true,
        target: 'es2018',
        loaders: {
          '.vue': 'ts',
        },
      }),
    ],
    external: ['vue'],
    treeshake: false,
  })
  await writeBundles(
    bundle,
    buildConfigEntries.map(([module, config]): OutputOptions => {
      return {
        format: config.format,
        dir: config.output.path,
        exports: module === 'cjs' ? 'named' : undefined,
        preserveModules: true,
        preserveModulesRoot: suRoot,
        sourcemap: true,
        entryFileNames: `[name].${config.ext}`,
      }
    })
  )
}

```
The problem is:
```
ReferenceError: __name is not defined
    at SortTemplate (eval at cloneSort (C:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\source-map-js@1.0.2\node_modules\source-map-js\lib\quick-sort.js:2:848), <anonymous>:3:107)
    at cloneSort (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\source-map-js@1.0.2\node_modules\source-map-js\lib\quick-sort.js:112:10)
    at exports.quickSort (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\source-map-js@1.0.2\node_modules\source-map-js\lib\quick-sort.js:128:19)
    at BasicSourceMapConsumer.SourceMapConsumer_parseMappings (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\source-map-js@1.0.2\node_modules\source-map-js\lib\source-map-consumer.js:604:9)
    at BasicSourceMapConsumer.get (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\source-map-js@1.0.2\node_modules\source-map-js\lib\source-map-consumer.js:70:12)     
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\source-map-js@1.0.2\node_modules\source-map-js\lib\source-map-consumer.js:136:23)
    at mapLines (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\@vue+compiler-sfc@3.3.4\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3672:18)
    at doCompileTemplate (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\@vue+compiler-sfc@3.3.4\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3644:13)      
    at compileTemplate (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\@vue+compiler-sfc@3.3.4\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3587:12)        
    at Object.compileScript (c:\Users\zhengshang\Desktop\storm-ui\node_modules\.pnpm\@vue+compiler-sfc@3.3.4\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:20306:53) 
```
I'd appreciate any help and am not sure if this is a Vite or esbuild, rollup problem

how can i solve

**Comment by zszhengshang** [comment]
Sorry.
Becase i found an issue https://github.com/evanw/esbuild/issues/1031.
And this https://github.com/evanw/esbuild/issues/1031#issuecomment-805285857
Is this same problem?

I try to use configuration in esbuild
```
esbuild({
    keepNames: false
}),
```
it doesn't work

**Comment by sxiong5** [comment]
> Sorry. Becase i found an issue #1031. And this [#1031 (comment)](https://github.com/evanw/esbuild/issues/1031#issuecomment-805285857) Is this same problem?
> 
> I try to use configuration in esbuild
> 
> ```
> esbuild({
>     keepNames: false
> }),
> ```
> 
> it doesn't work

Hey @evanw, have you solved this issue? I am encountering the same problem here. and `keepNames: false` doesn't work for me.

**Comment by HaiRongHaHA** [comment]
> > Sorry. Becase i found an issue #1031. And this [#1031 (comment)](https://github.com/evanw/esbuild/issues/1031#issuecomment-805285857) Is this same problem?
> > I try to use configuration in esbuild
> > ```
> > esbuild({
> >     keepNames: false
> > }),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it doesn't work
> 
> Hey @evanw, have you solved this issue? I am encountering the same problem here, and `keepNames: false` doesn't work for me either.
解决了吗？我也遇到了🥹

**Comment by sxiong5** [comment]
> > > Sorry. Becase i found an issue #1031. And this [#1031 (comment)](https://github.com/evanw/esbuild/issues/1031#issuecomment-805285857) Is this same problem?
> > > I try to use configuration in esbuild
> > > ```
> > > esbuild({
> > >     keepNames: false
> > > }),
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it doesn't work
> > 
> > 
> > Hey @evanw, have you solved this issue? I am encountering the same problem here, and `keepNames: false` doesn't work for me either.
> > 解决了吗？我也遇到了🥹

The [temporary solution](https://github.com/vuejs/core/issues/8303#issuecomment-1547540436) solved the issue; at least it worked for me.
这有个临时的解决方案可以试试。

**Comment by zhou-jincheng** [comment]
Here's a solution you can try [https://github.com/vitejs/vite-plugin-vue/issues/191#issuecomment-1623914994](@vitejs/plugin-vue), and I solved my problem.
