### ISSUE TITLE
livereload doesn't work in firefox/linux

### ISSUE THREAD

**Issue by ralyodio** [evanw/esbuild#3507]
```
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at new NodeError (node:internal/errors:406:5)
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1065:13)
    at file:///home/ettinger/src/hynt.us/hynt-web/node_modules/@primate/build/src/builders/esbuild/module.js:44:12
    at Array.forEach (<anonymous>)
    at inform (file:///home/ettinger/src/hynt.us/hynt-web/node_modules/@primate/build/src/builders/esbuild/module.js:43:11)
    at FSWatcher.<anonymous> (file:///home/ettinger/src/hynt.us/hynt-web/node_modules/@primate/build/src/builders/esbuild/module.js:141:13) {
  code: 'ERR_INVALID_STATE'
}
```

Node.js v20.9.0

I suspect its a wayland bug but not sure.

**Comment by evanw** [comment]
This error is coming from `node_modules/@primate/build/src/builders/esbuild/module.js`. That means it's coming from your code, not from esbuild. This doesn't look like a problem with esbuild. You'll need to look into this yourself.

**Comment by ralyodio** [comment]
yeah they said its coming from esbuild.

**Comment by evanw** [comment]
I'm closing this issue as a) it doesn't look like an esbuild issue to me and b) you ignored the issue reporting instructions and didn't provide a way to reproduce the issue.
