### ISSUE TITLE
Postinstall scripts fails

### ISSUE THREAD

**Issue by d-kah** [evanw/esbuild#3537]
Windows 10 Enterprise Edition
node v16.14.2
yarn 3.4.1

Running ``yarn`` in a turbo repo project
```
➤ YN0002: │ postcss-loader@npm:7.2.4 [2bcf2] doesn't provide @types/node (paeea3), requested by cosmiconfig-typescript-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 647ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yup@npm:1.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.22.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:2.0.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A5.2.2#~builtin<compat/typescript>::version=5.2.2&hash=1f5320: Cannot apply hunk #1
➤ YN0000: └ Completed in 9m 24s
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.17.18 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.19.3 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.54 must be built because it never has been before or the last one failed
➤ YN0009: │ esbuild@npm:0.18.20 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-f4458b06\build.log)
➤ YN0009: │ esbuild@npm:0.17.18 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-6d52bbde\build.log)
➤ YN0009: │ esbuild@npm:0.19.3 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-1be9cbbe\build.log)
➤ YN0009: │ esbuild@npm:0.18.20 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-aa63088c\build.log)
➤ YN0009: │ esbuild@npm:0.14.54 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-8bd1dfac\build.log)
➤ YN0000: └ Completed in 4s 846ms
➤ YN0000: Failed with errors in 9m 30s
```
Logs
```
 # This file contains the result of Yarn building a package (esbuild@npm:0.14.54)
# Script name: postinstall

node:child_process:828
    err = new Error(msg);
          ^

Error: Command failed: node C:\<myRepo>\node_modules\@badeball\cypress-configuration\node_modules\esbuild\bin\esbuild --version
node:child_process:869

    throw err;

    ^



<ref *1> Error: spawnSync C:\<myRepo>\node_modules\esbuild-windows-64\esbuild.exe UNKNOWN

    at Object.spawnSync (node:internal/child_process:1111:20)

    at spawnSync (node:child_process:814:24)

    at Object.execFileSync (node:child_process:860:15)

    at Object.<anonymous> (C:\<myRepo>\node_modules\@badeball\cypress-configuration\node_modules\esbuild\bin\esbuild:177:28)

    at Module._compile (node:internal/modules/cjs/loader:1103:14)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

    at node:internal/main/run_main_module:17:47 {

  errno: -4094,

  code: 'UNKNOWN',

  syscall: 'spawnSync C:\\<myRepo>\\node_modules\\esbuild-windows-64\\esbuild.exe',

  path: 'C:\\<myRepo>\\node_modules\\esbuild-windows-64\\esbuild.exe',

  spawnargs: [ '--version' ],

  error: [Circular *1],

  status: null,

  signal: null,

  output: null,

  pid: 0,

  stdout: null,

  stderr: null

}


    at checkExecSyncError (node:child_process:828:11)
    at Object.execFileSync (node:child_process:866:15)
    at validateBinaryVersion (C:\<myRepo>\node_modules\@badeball\cypress-configuration\node_modules\esbuild\install.js:89:32)
    at C:\<myRepo>\node_modules\@badeball\cypress-configuration\node_modules\esbuild\install.js:240:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1287) [Uint8Array] [
      110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
      114, 111,  99, 101, 115, 115,  58,  56,  54,  57,  13,  10,
       32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
      114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
       10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
      114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
      110,  99,  32,  67,  58,  92,  65,  98, 108,  97, 103, 101,
       92,  67, 111, 100, 101,  92,  77, 101, 105, 110, 101,  45,
       75, 102,  87,  45,
      ... 1187 more items
    ]
  ],
  pid: 22604,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1287) [Uint8Array] [
    110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
    114, 111,  99, 101, 115, 115,  58,  56,  54,  57,  13,  10,
     32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
    114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
     10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
    114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
    110,  99,  32,  67,  58,  92,  65,  98, 108,  97, 103, 101,
     92,  67, 111, 100, 101,  92,  77, 101, 105, 110, 101,  45,
     75, 102,  87,  45,
    ... 1187 more items
  ]
}

```

**Comment by evanw** [comment]
Version 0.14.54 is quite old at this point. It came out over a year ago, and esbuild's postinstall script has changed a lot since then. I don't support old versions of esbuild. You should try again with the latest version of esbuild.

**Comment by d-kah** [comment]
Removing Version 0.14.54 
and removing node_modules directory and yarn.lock
running ``yarn cache clean --all`` and then ``yarn``
I get result:
```
➤ YN0002: │ eslint-config-custom@workspace:dev/eslint-config-custom doesn't provide @babel/plugin-syntax-flow (pf0314), requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-custom@workspace:dev/eslint-config-custom doesn't provide @babel/plugin-transform-react-jsx (pefc8f), requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-custom@workspace:dev/eslint-config-custom doesn't provide @typescript-eslint/parser (p7572e), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ eslint-config-custom@workspace:dev/eslint-config-custom doesn't provide @typescript-eslint/parser (p284f2), requested by eslint-config-airbnb-typescript
➤ YN0060: │ eslint-config-custom@workspace:dev/eslint-config-custom provides eslint (pb432a) with version 7.32.0, which doesn't satisfy what eslint-plugin-flowtype requests
➤ YN0060: │ eslint-config-custom@workspace:dev/eslint-config-custom provides eslint (p19d65) with version 7.32.0, which doesn't satisfy what eslint-watch requests
➤ YN0002: │ portal@workspace:. doesn't provide react (p0454e), requested by react-dropzone
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 585ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.22.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zwitch@npm:2.0.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A5.3.3#~builtin<compat/typescript>::version=5.3.3&hash=1f5320: Cannot apply hunk #1
➤ YN0000: └ Completed in 10m 9s
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.19.9 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/client@npm:5.7.0 [fdf89] must be built because it never has been before or the last one failed
➤ YN0007: │ msw@npm:1.3.2 [4d051] must be built because it never has been before or the last one failed
➤ YN0007: │ msw@npm:1.3.2 [d4bbb] must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.34.0 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.31.3 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/engines@npm:5.7.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.3.100 [d336d] must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.34.0 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0009: │ esbuild@npm:0.19.9 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-4f5aa752\build.log)
➤ YN0009: │ esbuild@npm:0.18.20 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-b7cb818b\build.log)
➤ YN0009: │ esbuild@npm:0.18.20 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\K05V\AppData\Local\Temp\xfs-6e41dd4d\build.log)
➤ YN0007: │ portal@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ prisma@npm:5.7.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/client@npm:5.7.0 [1701c] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 42s 666ms
➤ YN0000: Failed with errors in 10m 53s
```
Logs
```
# This file contains the result of Yarn building a package (esbuild@npm:0.19.9)
# Script name: postinstall

node:child_process:828
    err = new Error(msg);
          ^

Error: Command failed: C:\Program Files\nodejs\node.exe C:\<myRepo>\node_modules\esbuild\bin\esbuild --version
node:child_process:869

    throw err;

    ^



<ref *1> Error: spawnSync C:\<myRepo>\node_modules\@esbuild\win32-x64\esbuild.exe UNKNOWN

    at Object.spawnSync (node:internal/child_process:1111:20)

    at spawnSync (node:child_process:814:24)

    at Object.execFileSync (node:child_process:860:15)

    at Object.<anonymous> (C:\<myRepo>\node_modules\esbuild\bin\esbuild:220:28)

    at Module._compile (node:internal/modules/cjs/loader:1103:14)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

    at node:internal/main/run_main_module:17:47 {

  errno: -4094,

  code: 'UNKNOWN',

  syscall: 'spawnSync C:\\<myRepo>\\node_modules\\@esbuild\\win32-x64\\esbuild.exe',

  path: 'C:\\<myRepo>\\node_modules\\@esbuild\\win32-x64\\esbuild.exe',

  spawnargs: [ '--version' ],

  error: [Circular *1],

  status: null,

  signal: null,

  output: null,

  pid: 0,

  stdout: null,

  stderr: null

}


    at checkExecSyncError (node:child_process:828:11)
    at Object.execFileSync (node:child_process:866:15)
    at validateBinaryVersion (C:\<myRepo>\node_modules\esbuild\install.js:98:28)
    at C:\<myRepo>\node_modules\esbuild\install.js:283:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1244) [Uint8Array] [
      110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
      114, 111,  99, 101, 115, 115,  58,  56,  54,  57,  13,  10,
       32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
      114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
       10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
      114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
      110,  99,  32,  67,  58,  92,  65,  98, 108,  97, 103, 101,
       92,  67, 111, 100, 101,  92,  77, 101, 105, 110, 101,  45,
       75, 102,  87,  45,
      ... 1144 more items
    ]
  ],
  pid: 22456,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1244) [Uint8Array] [
    110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
    114, 111,  99, 101, 115, 115,  58,  56,  54,  57,  13,  10,
     32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114,
    114,  59,  13,  10,  32,  32,  32,  32,  94,  13,  10,  13,
     10,  60, 114, 101, 102,  32,  42,  49,  62,  32,  69, 114,
    114, 111, 114,  58,  32, 115, 112,  97, 119, 110,  83, 121,
    110,  99,  32,  67,  58,  92,  65,  98, 108,  97, 103, 101,
     92,  67, 111, 100, 101,  92,  77, 101, 105, 110, 101,  45,
     75, 102,  87,  45,
    ... 1144 more items
  ]
}
```
Previously updating the node version in the terminal session to 18.19.0 or 20.10.0 gives the same result.

I am currently looking into whether my computer's corporate environment could be causing problems with Esbuild.

**Comment by evanw** [comment]
I'm not sure what's wrong here. One idea is that corporate anti-virus software can stop esbuild from running: https://esbuild.github.io/faq/#anti-virus-software. You might be able to test to see if that's the case by manually running `@esbuild/win32-x64/esbuild.exe --version` yourself.

Another thing to check could be how you are running esbuild, since there are several different ways to do it on Windows. Running using Command Prompt is different than running using Cygwin which is different than running using Windows Subsystem for Linux. Perhaps one of them isn't working due to a configuration issue (such as node thinking it's for a different platform), or perhaps one of them works when the other doesn't which would allow you to get past this configuration issue.

Those are the ideas I have for what might be happening here.

**Comment by d-kah** [comment]
Thanks a lot for your feedback.
Windows Defender is blocking Esbuild. I was not aware that the company I work for increased the IT security.
