### ISSUE TITLE
segfault with stylelint 16

### ISSUE THREAD

**Issue by martinpitt** [evanw/esbuild#3542]
Our projects recently got dependabot updates to [stylelint 15 → 16](https://github.com/cockpit-project/starter-kit/pull/752/files). This causes esbuild to [crash](https://cockpit-logs.us-east-1.linodeobjects.com/pull-752-20231212-215914-4722376c-fedora-39/log.html) like this:
```
fatal error: all goroutines are asleep - deadlock!
make: *** [Makefile:83: dist/manifest.json] Segmentation fault (core dumped)

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
	github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
	github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x59
main.runService(0x1)
	github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x4ed
main.main()
	github.com/evanw/esbuild/cmd/esbuild/main.go:240 +0xa29
[...]
```

For easier investigation I made a very minimal reproducer: [esbuild-crash.tar.gz](https://github.com/evanw/esbuild/files/13661676/esbuild-crash.tar.gz). Unpack it, and inside:

```
npm install
node build.js
```
It crashes with a segfault, albeit not with the extra "goroutine..." tracebacks from the real project. However, sometimes I also just see a segfault there without extra Go logs, that seems to be a timing issue.

When reverting stylelint to the 15.x versions, i. e. [that patch](https://github.com/cockpit-project/starter-kit/pull/752/files) reversed, it works.

**Comment by martinpitt** [comment]
This may be related to the number of CPU cores? There is a fairly consistent pattern that the crash happens on our CI machines (some have 16, some have 32 cores) and obviously my laptop (nproc says 8 cores, but it's hyperthreaded). But it never happened on Fedora's COPR builders -- it's not shown in the logs what kind of hw specs they have, but my guess is that it's not that many.

I just tried again and with just calling `node build.js` it crashes as reported. I can't use `systemd-run` to limit the number of CPUs as I do development in a container (toolbox). I checked that setting `$UV_THREADPOOL_SIZE` to 1, 8, 16, or 256 doesn't make any difference, it crashes consistently. Then I tried that in a QEMU VM with various number of virtual CPUs.

With 1 CPU, the  build works in the sense that it doesn't segfault. It fails with some stylelint errors, though:
```
  ✖  1:1  Unknown rule declaration-colon-newline-after.    declaration-colon-newline-after
  ✖  1:1  Unknown rule selector-list-comma-newline-after.  selector-list-comma-newline-after
  ✖  1:1  Unknown rule declaration-colon-space-before.     declaration-colon-space-before
  ✖  1:1  Unknown rule indentation.                        indentation
  ✖  1:1  Unknown rule max-line-length.                    max-line-length
```

which is a bit odd -- we use all these rules in production, but with stylelint 15.x, so I suppose that's just some dropped rules in 16.x. When dropping these 5 from `.stylelintrc.json`, the build succeeds. (I ran it 5 times)

But with 8 vCPUs it still succeeds. Presumably these vCPUs are weaker than the hardware ones, so it smells like some more subtle timing issue, as the deadlock message suggests. Same with 16 or 4 vCPUs.

**Comment by martinpitt** [comment]
I also tried locally with setting `$GOMAXPROCS` to 8, 4, 2, 1, but it doesn't seem to make any difference. (see https://pkg.go.dev/runtime). But I'm not sure if esbuild even honors that -- e.g. `GODEBUG="gctrace=1" node build.js` does not show any additional output.

**Comment by martinpitt** [comment]
Same crash with esbuild 0.9.10.

**Comment by evanw** [comment]
The latest release of esbuild [version 0.28.2](https://github.com/evanw/esbuild/releases/v0.28.2) solves one deadlock that was identified. See https://github.com/evanw/esbuild/issues/4503 and https://github.com/evanw/esbuild/pull/4506 for details.

Since I can't reproduce the deadlock reported here myself, I'm going to assume that it's the same as that one and close this issue. If it turns out it's not the same and it's still happening, we can reopen this issue again.
