### ISSUE TITLE
[ERROR] Unexpected end of file in JSON ../jsconfig.json:18:0 - File does not exist in project and node_modules

### ISSUE THREAD

**Issue by solongaldino** [evanw/esbuild#3628]
yarn build
yarn run v1.22.19
$ node esbuild.build.mjs
✘ [ERROR] Unexpected end of file in JSON

    ../jsconfig.json:18:0:
      18 │ 
         ╵ ^

/home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
../jsconfig.json:18:0: ERROR: Unexpected end of file in JSON
    at failureErrorWithLog (/home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:1651:15)
    at /home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:1057:7)
    at /home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/home/solon/Dev/company/work/app_react_web/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.11.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by evanw** [comment]
I’m closing this because you did not follow the issue reporting instructions:

> When reporting a bug or requesting a feature, please do the following:
>
> * Describe what esbuild is doing incorrectly and what it should be doing instead.
>
> * Provide a way to reproduce the issue. The best way to do this is to demonstrate the issue on the playground (https://esbuild.github.io/try/) and paste the URL here. A link to a minimal code sample with instructions for how to reproduce the issue may also work. Issues without a way to reproduce them may be closed.
