### ISSUE TITLE
"all goroutines are asleep - deadlock!" on a build

### ISSUE THREAD

**Issue by amrgamal97** [evanw/esbuild#3636]
The error occurs consistently when attempting to build the Angular v17 project on the DigitalOcean server.
No issues encountered when building the project locally.

steps I take:
```
sudo git clone https://github.com/amrgamal97/myprj.git
sudo npm install
sudo ng build
```
error message:
```
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
        github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x59
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x4ed
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:240 +0xa29
Killed

```

Environment:

```

Angular CLI: 17.1.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64
```

please fix it ASAP.

**Comment by btakita** [comment]
@amrgamal97 I have a [similar issue](https://github.com/evanw/esbuild/issues/3635). Are you using a monorepo? One possibility I'm exploring is that there are different copies of esbuild in different node_modules directories in the monorepo.

**Comment by danielrozenberg** [comment]
We're seeing this in our project when running on Linux, it seems to happen almost every time with Node 20.11.0, and almost not at all (but still sometimes) with Node 18.19.1 or Node 20.11.1

**Comment by erwinmombay** [comment]
we're also seeing this in our environment:

stack trace:

```
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
	github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
	github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x59
main.runService(0x1)
	github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x4ed
main.main()
	github.com/evanw/esbuild/cmd/esbuild/main.go:240 +0xa29

goroutine 18 [chan receive]:
main.runService.func1()
	github.com/evanw/esbuild/cmd/esbuild/service.go:98 +0x4a
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x1e5

goroutine 19 [chan receive]:
main.(*serviceType).sendRequest(0xc000228030, {0x93c580, 0xc0004f7170})
	github.com/evanw/esbuild/cmd/esbuild/service.go:192 +0xfa
main.runService.func3()
	github.com/evanw/esbuild/cmd/esbuild/service.go:125 +0x39
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:122 +0x31c
```

```
Operating System: Ubuntu 20.04.6 LTS
OSType: linux
```

**Comment by taras-kravets-ua** [comment]
The same issue on DigitalOcean ubuntu server after `ng build`

**Comment by csbenjamin** [comment]
I am also encountering the `fatal error: all goroutines are asleep - deadlock!` issue while using `esbuild` in my development environment. I am working on a Mac M1 Pro Max and facing this deadlock issue specifically when I have an Angular server running alongside multiple Node.js projects using `webpack --watch`. The deadlock occurs during the build process of an Angular application.

Interestingly, when I stop the Angular server and the `webpack --watch` processes, the build completes successfully without any errors. This seems to suggest some sort of resource contention or deadlock situation arising due to the concurrent execution of these processes.

Additionally, it's worth noting that my setup involves building the Angular application (version 17.1.3) inside a Docker container based on the `node:18.17.1` image. This setup has worked well for me until I encountered this deadlock issue with `esbuild`.

I am looking for any guidance or suggestions on how to resolve or work around this issue. Has anyone else experienced something similar in a Dockerized environment, particularly with the mentioned versions of Node.js and Angular, on a Mac M1 Pro Max? Any insights or recommendations would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by anlud** [comment]
This error occurred for me around 50% of the cases when I was building our Angular project within a docker container.
There was not really a pattern on when it would happen.
After increasing the available memory of the docker runtime from 4GB to 8GB of RAM the error does not occur any more. 

So this deadlock might be related to the available system memory running out.

**Comment by UmairMirza1** [comment]
https://github.com/evanw/esbuild/issues/3636#issuecomment-1990936837 

This solved my issue. I was running into the same stack trace with the error. 

`fatal error: all goroutines are asleep - deadlock!`

I was building locally on M1 pro 16GB where everything was working fine but the build was failing on VM.
Upgraded VM from 4GB to 8GB RAM and it seems to be fine now

**Comment by btakita** [comment]
I have plenty of available memory. But it's now happening consistently on my build.

**Comment by XhstormR** [comment]
I agree. This bug takes some time to occur.

**Comment by meDavidNS** [comment]
Thanks to a comment from @kentcdodds https://github.com/evanw/esbuild/issues/3287#issuecomment-1672026984 I was able to fix the same error in our pipelines that use playwright bdd tests after starting the angular dev server (using vite/esbuild under the hood). I added a `--watch=false` and deadlocks were never to be seen again.

**Comment by btakita** [comment]
I'm going to follow up on my anecdote. It seems that if the build take > 20s, the error may occur. If the build is <= 20s, the error does not seem to occur.

**Comment by AryanshMahato** [comment]
Still facing the same issue, any updates on this? I have 64 GB RAM, I don't memory could be limitation here.

**Comment by remorses** [comment]
This error can happen if you use the esbuild js api and your Node.js process is going out of memory, try increasing `--max-old-space-size`

**Comment by xxluke** [comment]
I came here as I had the same problem in a CI pipeline, but was now able to solve it by using a runner with more RAM (now 8 instead of 4 GB).

I'm using it for Angular + Playwright with coverage

**Comment by sansubed** [comment]
> This error can happen if you use the esbuild js api and your Node.js process is going out of memory, try increasing `--max-old-space-size`

This resolved my issue.

**Comment by eliasm307** [comment]
I had this issue and tried suggestions like `increasing --max-old-space-size` but it didnt work for me, however my issue ended up being due to issues with my RAM. You can run [memtest86](https://www.memtest86.com/) to check for RAM issues (any errors is bad)

After removing/replacing RAM cards with issues, I have not had the "all goroutines are asleep - deadlock!" issue

**Comment by HitkoDev** [comment]
I've started noticing this in my Angular 21 app, and I'm 100% it has nothing to do with RAM:
- the build processes never use more than 300 MB of RAM, and I have over 32 GB available
- even setting `--max-old-space-size` to 32 GB doesn't help
- builds never last more than 2 seconds, whether successful or no
- this happens occasionally, only when running a clean build / watch, or when switching between the two
- re-running the same build a few times fixes it
- after a successful build, subsequent builds of the same type never throw this error, unless I switch build configuration between them
- rebuilds in watch mode never fail either
- this only happens with two of my libraries, one is pretty big, but the other one only has 2 simple components and one tiny service with no third-party dependencies; there are 5 other libraries of varying size and complexity in the same project, using the same configuration and `node_modules`, yet they never fail to build like this

Is there a way to see what each goroutine is trying to access when this happens? To me it seems the issue has more to do with concurrent filesystem / memory access.

**Comment by btakita** [comment]
@HitkoDev Clone the project & add some debug `std.fmt.print` statements & test?

**Comment by zuhairak** [comment]
I also get this error intermittently when I run a dev environment in Angular 21 - WSL2 , mine got solved when I freed up some memory closing apps.

``` 
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help
Killed
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
        github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x51
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x50c
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:252 +0xb6b

goroutine 7 [chan receive]:
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:98 +0x45
created by main.runService in goroutine 1
        github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x1db

goroutine 8 [chan receive]:
main.(*serviceType).sendRequest(0xc000190390, {0x9973a0, 0xc015386ed0})
        github.com/evanw/esbuild/cmd/esbuild/service.go:192 +0x12b
main.runService.func3()
        github.com/evanw/esbuild/cmd/esbuild/service.go:125 +0x3e
created by main.runService in goroutine 1
        github.com/evanw/esbuild/cmd/esbuild/service.go:122 +0x30d```

**Comment by pit-nrw** [comment]
> I've started noticing this in my Angular 21 app, and I'm 100% it has nothing to do with RAM:
> 
> * the build processes never use more than 300 MB of RAM, and I have over 32 GB available
> * even setting `--max-old-space-size` to 32 GB doesn't help
> * builds never last more than 2 seconds, whether successful or no
> * this happens occasionally, only when running a clean build / watch, or when switching between the two
> * re-running the same build a few times fixes it
> * after a successful build, subsequent builds of the same type never throw this error, unless I switch build configuration between them
> * rebuilds in watch mode never fail either
> * this only happens with two of my libraries, one is pretty big, but the other one only has 2 simple components and one tiny service with no third-party dependencies; there are 5 other libraries of varying size and complexity in the same project, using the same configuration and `node_modules`, yet they never fail to build like this
> 
> Is there a way to see what each goroutine is trying to access when this happens? To me it seems the issue has more to do with concurrent filesystem / memory access.

That is exactly the behavior I am experiencing. The error only occurs on subsequent builds.  I am developing in a Docker container, and the system has 128 GB of RAM, so I don't think it's a memory issue.

**Comment by cheesi** [comment]
I can confirm, that I see similar error messages sometimes, when using Angular v21 + vitest, especially with `ng test`:
```
PASS  Waiting for file changes...
       press h to show help, press q to quit
fatal error: all goroutines are asleep - deadlock!
⏎
goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
	github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
	github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x8c
main.runService(0x1)
	github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x43c
main.main()
	github.com/evanw/esbuild/cmd/esbuild/main.go:252 +0xa70

goroutine 7 [chan receive]:
main.runService.func1()
	github.com/evanw/esbuild/cmd/esbuild/service.go:98 +0x40
created by main.runService in goroutine 1
	github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x180

goroutine 8 [chan receive]:
main.(*serviceType).sendRequest(0x140000eaed0, {0x102e46ba0, 0x14000133ef0})
	github.com/evanw/esbuild/cmd/esbuild/service.go:192 +0x134
main.runService.func3()
	github.com/evanw/esbuild/cmd/esbuild/service.go:125 +0x44
created by main.runService in goroutine 1
	github.com/evanw/esbuild/cmd/esbuild/service.go:122 +0x2b0
```

**Comment by Rush** [comment]
Seeing the same issue with Angular 21 - anyone has ideas?

**Comment by ryandegruyter** [comment]
Also started getting this one with Angular 21 and trying to serve a dev server.

**Comment by yourcodesnotworking** [comment]
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/evanw/esbuild/internal/helpers.(*ThreadSafeWaitGroup).Wait(...)
        github.com/evanw/esbuild/internal/helpers/waitgroup.go:36
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0x53
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:160 +0x4c3
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:252 +0xb75

goroutine 7 [chan receive]:
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:98 +0x45
created by main.runService in goroutine 1
        github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x1ce

goroutine 8 [chan receive]:
main.(*serviceType).sendRequest(0xc0000deed0, {0x9f48c0, 0xc010708480})
        github.com/evanw/esbuild/cmd/esbuild/service.go:192 +0x12b
main.runService.func3()
        github.com/evanw/esbuild/cmd/esbuild/service.go:125 +0x3e
created by main.runService in goroutine 1
        github.com/evanw/esbuild/cmd/esbuild/service.go:122 +0x2d0

I happens everytime if you refresh the pages after angular rebuilt.

**Comment by Akxe** [comment]
Sadly, this issue is also real for Angular 22, and I use NX for the monorepo.

**Comment by evanw** [comment]
The latest release of esbuild [version 0.28.2](https://github.com/evanw/esbuild/releases/v0.28.2) solves one deadlock that was identified. See https://github.com/evanw/esbuild/issues/4503 and https://github.com/evanw/esbuild/pull/4506 for details.

Since I can't reproduce the deadlock reported here myself, I'm going to assume that it's the same as that one and close this issue. If it turns out it's not the same and it's still happening, we can reopen this issue again.
