### ISSUE TITLE
panic: Internal error: failed to parse runtime with `--supported:object-accessors=false`

### ISSUE THREAD

**Issue by hyrious** [evanw/esbuild#3794]
**Reproduction**

```console
> echo '' | esbuild --supported:object-accessors=false
panic: Internal error: failed to parse runtime:
✘ [ERROR] Transforming object accessors to the configured target environment is not supported yet

    <runtime>:179:39:
      179 │ ...wnPropDesc(k < 4 ? target : { get [name]() { return __privateG...
          ╵                                  ~~~

✘ [ERROR] Transforming object accessors to the configured target environment is not supported yet

    <runtime>:179:90:
      179 │ ... __privateGet(this, extra) }, set [name](x) { return __private...
          ╵                                  ~~~


goroutine 19 [running]:
github.com/evanw/esbuild/internal/bundler.(*runtimeCache).parseRuntime(_, _)
        github.com/evanw/esbuild/internal/bundler/bundler.go:3167 +0x66c
github.com/evanw/esbuild/internal/bundler.ScanBundle.func2()
        github.com/evanw/esbuild/internal/bundler/bundler.go:1285 +0x88
created by github.com/evanw/esbuild/internal/bundler.ScanBundle
        github.com/evanw/esbuild/internal/bundler/bundler.go:1284 +0x93b
```

[**Playground Link**](https://esbuild.github.io/try/#dAAwLjIxLjQALS1zdXBwb3J0ZWQ6b2JqZWN0LWFjY2Vzc29ycz1mYWxzZQA)

> [!NOTE]
> Openning this link you will see the page stops working and in the devtools console there is a `exit code: 2` warning.

**Comment by evanw** [comment]
Thanks for the report. I'll address this in the next release and also add tests to avoid this in the future. In the meantime, a workaround is to also add `--supported:object-extensions=false`.
