### ISSUE TITLE
Invalid code generated, fails to load because variable is used during its declaration

### ISSUE THREAD

**Issue by jrieken** [evanw/esbuild#3823]
* open https://esbuild.github.io/try/#YgAwLjIzLjAAe2J1bmRsZTp0cnVlLCBmb3JtYXQ6ICdlc20nLCBtaW5pZnk6IGZhbHNlLCBwbGF0Zm9ybTogJ2Jyb3dzZXInfQBlAGVudHJ5LmpzAGltcG9ydCB7T3ZlcnZpZXdSdWxlckZlYXR1cmV9IGZyb20gJy4vZmlsZTIudHMnOwoKbmV3IE92ZXJ2aWV3UnVsZXJGZWF0dXJlKCk7AAB0c2NvbmZpZy5qc29uAHsKCSJjb21waWxlck9wdGlvbnMiOiB7CgkJImV4cGVyaW1lbnRhbERlY29yYXRvcnMiOiB0cnVlLAoJCSJ1c2VEZWZpbmVGb3JDbGFzc0ZpZWxkcyI6IGZhbHNlLAoJfQp9CgAAZmlsZTIudHMAZXhwb3J0IGNsYXNzIE92ZXJ2aWV3UnVsZXJGZWF0dXJlIGV4dGVuZHMgRGlzcG9zYWJsZSB7Cglwcml2YXRlIHN0YXRpYyByZWFkb25seSBPTkVfT1ZFUlZJRVdfV0lEVEggPSAxNTsKCXB1YmxpYyBzdGF0aWMgcmVhZG9ubHkgRU5USVJFX0RJRkZfT1ZFUlZJRVdfV0lEVEggPSBPdmVydmlld1J1bGVyRmVhdHVyZS5PTkVfT1ZFUlZJRVdfV0lEVEggKiAyOwoJcHVibGljIHJlYWRvbmx5IHdpZHRoID0gT3ZlcnZpZXdSdWxlckZlYXR1cmUuRU5USVJFX0RJRkZfT1ZFUlZJRVdfV0lEVEg7CgoJY29uc3RydWN0b3IoCgkJcHJpdmF0ZSByZWFkb25seSBfZWRpdG9yczogRGlmZkVkaXRvckVkaXRvcnMsCgkJcHJpdmF0ZSByZWFkb25seSBfcm9vdEVsZW1lbnQ6IEhUTUxFbGVtZW50LAoJCXByaXZhdGUgcmVhZG9ubHkgX2RpZmZNb2RlbDogSU9ic2VydmFibGU8RGlmZkVkaXRvclZpZXdNb2RlbCB8IHVuZGVmaW5lZD4sCgkJcHJpdmF0ZSByZWFkb25seSBfcm9vdFdpZHRoOiBJT2JzZXJ2YWJsZTxudW1iZXI+LAoJCXByaXZhdGUgcmVhZG9ubHkgX3Jvb3RIZWlnaHQ6IElPYnNlcnZhYmxlPG51bWJlcj4sCgkJcHJpdmF0ZSByZWFkb25seSBfbW9kaWZpZWRFZGl0b3JMYXlvdXRJbmZvOiBJT2JzZXJ2YWJsZTxFZGl0b3JMYXlvdXRJbmZvIHwgbnVsbD4sCgkJQElUaGVtZVNlcnZpY2UgcHJpdmF0ZSByZWFkb25seSBfdGhlbWVTZXJ2aWNlOiBJVGhlbWVTZXJ2aWNlLAoJKSB7CgkJc3VwZXIoKTsKCgoKCX0KfQo
* notice the last/second static-initialise block referencing `OverviewRulerFeature` before being declared

```
// file2.ts
var OverviewRulerFeature = class extends Disposable {
  constructor(_editors, _rootElement, _diffModel, _rootWidth, _rootHeight, _modifiedEditorLayoutInfo, _themeService) {
    super();
    this._editors = _editors;
    this._rootElement = _rootElement;
    this._diffModel = _diffModel;
    this._rootWidth = _rootWidth;
    this._rootHeight = _rootHeight;
    this._modifiedEditorLayoutInfo = _modifiedEditorLayoutInfo;
    this._themeService = _themeService;
    this.width = OverviewRulerFeature.ENTIRE_DIFF_OVERVIEW_WIDTH;
  }
  static {
    this.ONE_OVERVIEW_WIDTH = 15;
  }
  static {
    this.ENTIRE_DIFF_OVERVIEW_WIDTH = OverviewRulerFeature.ONE_OVERVIEW_WIDTH * 2;
//                                    ^^^^^^^^^^^^^^^^^^
//                                    This CANNOT be accessed
  }
};
OverviewRulerFeature = __decorateClass([
  __decorateParam(6, IThemeService)
], OverviewRulerFeature);

```

**Comment by evanw** [comment]
Sorry about this. The class lowering transforms are extremely complicated as they all interact with each other. I'm not surprised to hear that there's another edge case like this. FWIW it's possible that using `supported: { 'class-static-blocks': false }` may fix this problem (by telling esbuild to avoid lowering static class fields into static blocks). [Here's a live link.](https://esbuild.github.io/try/#YgAwLjIzLjAAewogIGJ1bmRsZTogdHJ1ZSwKICBmb3JtYXQ6ICdlc20nLAogIG1pbmlmeTogZmFsc2UsCiAgcGxhdGZvcm06ICdicm93c2VyJywKICBzdXBwb3J0ZWQ6IHsKICAgICdjbGFzcy1zdGF0aWMtYmxvY2tzJzogZmFsc2UsCiAgfSwKfQBlAGVudHJ5LmpzAGltcG9ydCB7Rm9vfSBmcm9tICcuL2ZpbGUyLnRzJzsKCm5ldyBGb28oKTsAAHRzY29uZmlnLmpzb24AewogICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAiZXhwZXJpbWVudGFsRGVjb3JhdG9ycyI6IHRydWUsCiAgICAidXNlRGVmaW5lRm9yQ2xhc3NGaWVsZHMiOiBmYWxzZQogIH0KfQoAAGZpbGUyLnRzAGV4cG9ydCBjbGFzcyBGb28gZXh0ZW5kcyBEaXNwb3NhYmxlIHsKCXByaXZhdGUgc3RhdGljIHJlYWRvbmx5IEEgPSAxNTsKCXB1YmxpYyBzdGF0aWMgcmVhZG9ubHkgQiA9IEZvby5BICogMjsKCXB1YmxpYyByZWFkb25seSB3aWR0aCA9IEZvby5COwoKCWNvbnN0cnVjdG9yKAoJCUBJVGhlbWVTZXJ2aWNlIHByaXZhdGUgcmVhZG9ubHkgX3RoZW1lU2VydmljZTogSVRoZW1lU2VydmljZSwKCSkgewoJCXN1cGVyKCk7Cgl9Cn0K)

**Comment by jrieken** [comment]
Thanks @evanw! That trick works nicely, didn't even know `supported` exists.

**Comment by WilliamABradley** [comment]
@evanw I'm not sure if this is related, I'm getting this weird result from code executed via tsx (Which uses esbuild under the hood)

Some tidbits:
```ts
export const Property = (options: PropertyOptions): PropertyDecorator => {
  return (...args) => {
    console.log("Property", inspect(args));
    const [target, property] = args;
    const targetName = target.constructor.name;
    if (typeof property === "symbol") {
      throw new Error(`Symbol properties on ${targetName} are not supported`);
    }
    if (property === "type") {
      throw new Error(`Property name 'type' on '${targetName}' is reserved`);
    }
    let properties = PropertyContext.get(targetName);
    if (!properties) {
      properties = new Map();
      PropertyContext.set(targetName, properties);
    }
    properties.set(property, options);
  };
};

export abstract class DataModel {
  static isDataModel = true;

  static context() {
    return modelContextFrom(this.prototype.constructor);
  }

  context() {
    return modelContextFrom(this.constructor);
  }
}

@Model({
  name: "State",
  description: "A state object",
})
export class State extends DataModel {
  constructor(data?: DataModelInput<State>) {
    super();
    loadModel(this, data);
  }

  @Property({ type: String })
  key: string;

  @Property({ type: String })
  value: string;

  @Property({ converter: DateTimeValueConverter })
  createdAt: Temporal.Instant;

  @Property({ converter: DateTimeValueConverter })
  updatedAt: Temporal.Instant;
}
```

Log:
```
Property [
  undefined,
  {
    kind: 'field',
    name: 'key',
    metadata: [Object: null prototype] {},
    addInitializer: [Function: addInitializer],
    static: false,
    private: false,
    access: {
      has: [Function (anonymous)],
      get: [Function (anonymous)],
      set: [Function (anonymous)]
    }
  }
]
TypeError: Cannot read properties of undefined (reading 'constructor')
    at <anonymous> (c:\Programming\Github\will-app\packages\models\src\utils\decorators.ts:22:31)
    at __decorateElement (file:///C:/Programming/Github/will-app/packages/models/src/api/state.ts:1:2537)
    at <anonymous> (c:\Programming\Github\will-app\packages\models\src\api\state.ts:23:3)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at SyncRun.run (c:\Programming\Github\will-app\scripts\src\commands\sync\run.ts:33:25)
    at async SyncRun._run (C:\Programming\Github\will-app\node_modules\.pnpm\@oclif+core@4.0.31\node_modul
es\@oclif\core\lib\command.js:302:22)
    at async Config.runCommand (C:\Programming\Github\will-app\node_modules\.pnpm\@oclif+core@4.0.31\node_
modules\@oclif\core\lib\config\config.js:425:25)
    at async run (C:\Programming\Github\will-app\node_modules\.pnpm\@oclif+core@4.0.31\node_modules\@oclif
\core\lib\main.js:95:16)
    at async file:///C:/Programming/Github/will-app/scripts/bin/dev.js:6:1
```

I'm having a really hard time building a reproducable exemplar in the esbuild try in browser tool, and even calling esbuild with the following: `esbuild src/commands/sync/run.ts --bundle --outdir=out --format
=esm --platform=node --banner:js="import { createRequire } from 'module'; const require = createRequire(im
port.meta.url);"`

Let me know if you need any more information in any which direction which might help narrow down the cause of this.

**Comment by WilliamABradley** [comment]
I found the transpiled source from tsx's cache:

```js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __knownSymbol = (name, symbol) =>
  (symbol = Symbol[name]) ? symbol : Symbol.for("Symbol." + name);
var __typeError = (msg) => {
  throw TypeError(msg);
};
var __defNormalProp = (obj, key, value) =>
  key in obj
    ? __defProp(obj, key, {
        enumerable: true,
        configurable: true,
        writable: true,
        value,
      })
    : (obj[key] = value);
var __name = (target, value) =>
  __defProp(target, "name", { value, configurable: true });
var __decoratorStart = (base) => [
  ,
  ,
  ,
  __create(base?.[__knownSymbol("metadata")] ?? null),
];
var __decoratorStrings = [
  "class",
  "method",
  "getter",
  "setter",
  "accessor",
  "field",
  "value",
  "get",
  "set",
];
var __expectFn = (fn) =>
  fn !== void 0 && typeof fn !== "function"
    ? __typeError("Function expected")
    : fn;
var __decoratorContext = (kind, name, done, metadata, fns) => ({
  kind: __decoratorStrings[kind],
  name,
  metadata,
  addInitializer: (fn) =>
    done._
      ? __typeError("Already initialized")
      : fns.push(__expectFn(fn || null)),
});
var __decoratorMetadata = (array, target) =>
  __defNormalProp(target, __knownSymbol("metadata"), array[3]);
var __runInitializers = (array, flags, self, value) => {
  for (var i = 0, fns = array[flags >> 1], n = fns && fns.length; i < n; i++)
    flags & 1 ? fns[i].call(self) : (value = fns[i].call(self, value));
  return value;
};
var __decorateElement = (array, flags, name, decorators, target, extra) => {
  var fn,
    it,
    done,
    ctx,
    access,
    k = flags & 7,
    s = !!(flags & 8),
    p = !!(flags & 16);
  var j = k > 3 ? array.length + 1 : k ? (s ? 1 : 2) : 0,
    key = __decoratorStrings[k + 5];
  var initializers = k > 3 && (array[j - 1] = []),
    extraInitializers = array[j] || (array[j] = []);
  var desc =
    k &&
    (!p && !s && (target = target.prototype),
    k < 5 &&
      (k > 3 || !p) &&
      __getOwnPropDesc(
        k < 4
          ? target
          : {
              get [name]() {
                return __privateGet(this, extra);
              },
              set [name](x) {
                return __privateSet(this, extra, x);
              },
            },
        name
      ));
  k
    ? p && k < 4 && __name(extra, (k > 2 ? "set " : k > 1 ? "get " : "") + name)
    : __name(target, name);
  for (var i = decorators.length - 1; i >= 0; i--) {
    ctx = __decoratorContext(k, name, (done = {}), array[3], extraInitializers);
    if (k) {
      (ctx.static = s),
        (ctx.private = p),
        (access = ctx.access =
          { has: p ? (x) => __privateIn(target, x) : (x) => name in x });
      if (k ^ 3)
        access.get = p
          ? (x) =>
              (k ^ 1 ? __privateGet : __privateMethod)(
                x,
                target,
                k ^ 4 ? extra : desc.get
              )
          : (x) => x[name];
      if (k > 2)
        access.set = p
          ? (x, y) => __privateSet(x, target, y, k ^ 4 ? extra : desc.set)
          : (x, y) => (x[name] = y);
    }
    (it = (0, decorators[i])(
      k
        ? k < 4
          ? p
            ? extra
            : desc[key]
          : k > 4
          ? void 0
          : { get: desc.get, set: desc.set }
        : target,
      ctx
    )),
      (done._ = 1);
    if (k ^ 4 || it === void 0)
      __expectFn(it) &&
        (k > 4
          ? initializers.unshift(it)
          : k
          ? p
            ? (extra = it)
            : (desc[key] = it)
          : (target = it));
    else if (typeof it !== "object" || it === null)
      __typeError("Object expected");
    else
      __expectFn((fn = it.get)) && (desc.get = fn),
        __expectFn((fn = it.set)) && (desc.set = fn),
        __expectFn((fn = it.init)) && initializers.unshift(fn);
  }
  return (
    k || __decoratorMetadata(array, target),
    desc && __defProp(target, name, desc),
    p ? (k ^ 4 ? extra : desc) : target
  );
};
var __publicField = (obj, key, value) =>
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
var __accessCheck = (obj, member, msg) =>
  member.has(obj) || __typeError("Cannot " + msg);
var __privateIn = (member, obj) =>
  Object(obj) !== obj
    ? __typeError('Cannot use the "in" operator on this value')
    : member.has(obj);
var __privateGet = (obj, member, getter) => (
  __accessCheck(obj, member, "read from private field"),
  getter ? getter.call(obj) : member.get(obj)
);
var __privateSet = (obj, member, value, setter) => (
  __accessCheck(obj, member, "write to private field"),
  setter ? setter.call(obj, value) : member.set(obj, value),
  value
);
var __privateMethod = (obj, member, method) => (
  __accessCheck(obj, member, "access private method"), method
);
var _updatedAt_dec,
  _createdAt_dec,
  _value_dec,
  _key_dec,
  _a,
  _State_decorators,
  _init;
import {
  DataModel,
  DateTimeValueConverter,
  Model,
  OmitModel,
  Property,
  loadModel,
} from "#utils";
_State_decorators = [Model({ name: "State", description: "A state object" })];
let _State = class _State extends ((_a = DataModel),
(_key_dec = [Property({ type: String })]),
(_value_dec = [Property({ type: String })]),
(_createdAt_dec = [Property({ converter: DateTimeValueConverter })]),
(_updatedAt_dec = [Property({ converter: DateTimeValueConverter })]),
_a) {
  constructor(data) {
    super();
    __publicField(this, "key", __runInitializers(_init, 8, this)),
      __runInitializers(_init, 11, this);
    __publicField(this, "value", __runInitializers(_init, 12, this)),
      __runInitializers(_init, 15, this);
    __publicField(this, "createdAt", __runInitializers(_init, 16, this)),
      __runInitializers(_init, 19, this);
    __publicField(this, "updatedAt", __runInitializers(_init, 20, this)),
      __runInitializers(_init, 23, this);
    loadModel(this, data);
  }
};
_init = __decoratorStart(_a);
__decorateElement(_init, 5, "key", _key_dec, _State);
__decorateElement(_init, 5, "value", _value_dec, _State);
__decorateElement(_init, 5, "createdAt", _createdAt_dec, _State);
__decorateElement(_init, 5, "updatedAt", _updatedAt_dec, _State);
_State = __decorateElement(_init, 0, "State", _State_decorators, _State);
__name(_State, "State");
__runInitializers(_init, 1, _State);
let State = _State;
class UpdateState extends OmitModel(State, ["createdAt", "updatedAt"]) {
  static {
    __name(this, "UpdateState");
  }
  constructor(data) {
    super();
    loadModel(this, data);
  }
}
export { State, UpdateState };
```

There must be something wrong with the esbuild flags that TSX is using, because this command seems to be working correctly: 

```
esbuild src/local.ts --bundle --outdir=out --format=esm --platform=node --banner:js="import { createRequire } from 'module'; const require = createRequire(import.meta.url);" --keep-names --target=node20.18.0 --minify-whitespace
```
