### ISSUE TITLE
ReferenceError in strict mode

### ISSUE THREAD

**Issue by wdzeng** [evanw/esbuild#3882]
I found cjs files generated from ts files sometimes throws ReferenceError. I found the problem with a project using [`adm-zip`](https://www.npmjs.com/package/adm-zip) library.

## Reproduction

Using Node.js v20.15.0.

### Steps

1. package.json
```json
{
  "dependencies": {
    "@types/adm-zip": "0.5.5",
    "adm-zip": "0.5.15",
    "esbuild": "0.23.0"
  }
}
```
2. tsconfig.json
```json
{
  "compilerOptions": {
    "strict": true
  }
}
```
3. test.ts
```ts
import AdmZip from 'adm-zip'
const zip = new AdmZip()
zip.addFile('test.txt', Buffer.from('hello world'))
zip.writeZip('/tmp/test.zip')
```
4. Run `npm i && npx esbuild test.ts --platform=node --target=node20 --bundle --outfile=/tmp/test.cjs && node /tmp/test.cjs`

### Expected Result

/tmp/test.cjs generates /tmp/test.zip.

### Actual Result

/tmp/test.cjs throws `ReferenceError` and fails.

```
ReferenceError: totalEntries is not defined
    at Object.compressToBuffer (/tmp/test.cjs:1790:24)
    at Object.writeZip (/tmp/test.cjs:2629:30)
    at Object.<anonymous> (/tmp/test.cjs:2688:5)
```

## Hints

1. Running `node /path/to/the/following/script.js` will succeed.

```js
"use strict";
const AdmZip = require('adm-zip')
const zip = new AdmZip()
zip.addFile('test.txt', Buffer.from('hello world'))
zip.writeZip('/tmp/test.zip')
```

2. If we remove `"strict": true` in the tsconfig.json, the reproduction will give the expected result.

**Comment by wdzeng** [comment]
Oh thanks!
