### ISSUE TITLE
@aws-sdk/lib-storage File Upload is not working at esbuild@0.19.3 

### ISSUE THREAD

**Issue by eXpertise7** [evanw/esbuild#3893]
**The previous version in which this bug was not present was**
Before Migrating to the `esbuild` system. This feature works with `webpack` builder.

**Description**
I am trying to upload images to AWS but because of the Migrating to the new build system it is not working anymore

**Minimal Reproduction**
```
import { Upload } from "@aws-sdk/lib-storage";
import { S3Client } from "@aws-sdk/client-s3";


  const parallelUploads3 = new Upload({
    client:  new S3Client({}),
    params: { Bucket, Key, Body },
  });
  parallelUploads3.on("httpUploadProgress", (progress) => {
    console.log(progress);
  });

parallelUploads3.done() .then(
                (data) => {
                   console.log(data)
                },
                (err: any) => {
                    console.log(err)
                },
            );
```

```
Exception or Error
TypeError: Cannot read properties of undefined (reading 'done')
    at getChunkStream.js:5:5
    at Generator.next (<anonymous>)
    at resume (chunk-CDW57LCT.js?v=b9e9dd30:100:27)
    at chunk-CDW57LCT.js?v=b9e9dd30:106:63
    at new ZoneAwarePromise (zone.js:1425:21)
    at it.<computed> [as next] (chunk-CDW57LCT.js?v=b9e9dd30:106:38)
    at Upload.<anonymous> (Upload.js:130:9)
    at Generator.next (<anonymous>)
    at chunk-CDW57LCT.js?v=b9e9dd30:90:61
    at new ZoneAwarePromise (zone.js:1425:21)
```

**Environment**

Angular CLI: 17.3.8
Node: 18.13.0
Package Manager: npm 8.19.4
OS: darwin x64

Angular: 17.3.10
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
```
@angular-devkit/architect: 0.1703.8
@angular-devkit/build-angular: 17.3.8
@angular-devkit/core: 17.3.8
@angular-devkit/schematics: 17.3.8
@angular/cli: 17.3.8
@angular/google-maps: 16.2.14
@schematics/angular: 17.3.8
rxjs: 7.8.1
typescript: 5.4.5
zone.js: 0.14.6
```

Helpful link can be found here: **https://github.com/angular/angular-cli/issues/27771#issuecomment-2304376589**.

**Comment by eXpertise7** [comment]
@evanw If any further details are needed, I'm available to explain.

**Comment by markostojkov** [comment]
@evanw We are experiencing the same issue

**Comment by Austinb** [comment]
Any movement on this issue?  Was racking my brain as to why an upgrade to aws-sdk v3 for Angular 17 caused uploads to break.  Using the code available at https://stackoverflow.com/a/78877935 works around the issue but the file upload object needs to be fixed.

**Comment by AmebaBrain** [comment]
+1
it's pity that on the latest Angular (19th) you couldn't integrate with the AWS because of such crazy internal build error

@Austinb 
God bless you for your comment!

**Comment by edotassi** [comment]
is there any update regarding this issue?

**Comment by JanST123GS** [comment]
Still no movement? :(

**Comment by JanST123GS** [comment]
It seems to be fixed with @angular/cli 20.3.10.

Can someone confirm?

**Comment by mixer904** [comment]
The issue still exists, but I found a workaround for my project.
Update your `angular.json` and exclude `@aws-sdk/lib-storage` in the prebundle section:

```json
{
  "projects": {
    "your-project": {
      "architect": {
        "serve": {
          "builder": "@angular/build:dev-server",
          "options": {
            "prebundle": {
              "exclude": [
                "@aws-sdk/lib-storage"
              ]
            }
          }
        }
      }
    }
  }
}
```

**Comment by cherryoff** [comment]
This issue is still reproducible with esbuild 0.28.1 and Angular 21. 
Problem appears for continuously-polled shared async generators. I reduced the AWS case to a standalone reproduction that does not use Angular, Zone.js, AWS, or network requests. Two consumers of the same downleveled async generator trigger `Cannot read properties of undefined (reading 'done')`, while one consumer and native async generators work correctly. 
The generated __asyncGenerator helper appears to share the mutable wait value between .next() invocations, allowing an earlier completion handler to clear the queue while later calls are still pending. 
Using queueSize: 1 in @aws-sdk/lib-storage avoids the race.
