### ISSUE TITLE
Null target on property decorator

### ISSUE THREAD

**Issue by WilliamABradley** [evanw/esbuild#3960]
May be related to https://github.com/evanw/esbuild/issues/3823

I've been trying to debug an error from tsx, which appears to be an esbuild error.

I'm having a really hard time building a reproducable exemplar in the esbuild try in browser tool, and even calling esbuild with the following: 

```
esbuild src/commands/sync/run.ts --bundle --outdir=out --format =esm --platform=node --banner:js="import { createRequire } from 'module'; const require = createRequire(import.meta.url);"
```

I'm pretty sure this is an esbuild issue since it contains the transpiled __decorateElement function in the stacktrace.

Log:
```
Property [
  undefined,
  {
    kind: 'field',
    name: 'key',
    metadata: [Object: null prototype] {},
    addInitializer: [Function: addInitializer],
    static: false,
    private: false,
    access: {
      has: [Function (anonymous)],
      get: [Function (anonymous)],
      set: [Function (anonymous)]
    }
  }
]
TypeError: Cannot read properties of undefined (reading 'constructor')
    at <anonymous> (c:\Programming\Github\will-app\packages\models\src\utils\decorators.ts:22:31)
    at __decorateElement (file:///C:/Programming/Github/will-app/packages/models/src/api/state.ts:1:2537)
    at <anonymous> (c:\Programming\Github\will-app\packages\models\src\api\state.ts:23:3)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at SyncRun.run (c:\Programming\Github\will-app\scripts\src\commands\sync\run.ts:33:25)
    at async SyncRun._run (C:\Programming\Github\will-app\node_modules\.pnpm\@oclif+core@4.0.31\node_modul
es\@oclif\core\lib\command.js:302:22)
    at async Config.runCommand (C:\Programming\Github\will-app\node_modules\.pnpm\@oclif+core@4.0.31\node_
modules\@oclif\core\lib\config\config.js:425:25)
    at async run (C:\Programming\Github\will-app\node_modules\.pnpm\@oclif+core@4.0.31\node_modules\@oclif
\core\lib\main.js:95:16)
    at async file:///C:/Programming/Github/will-app/scripts/bin/dev.js:6:1
```

A sample of the source:
```ts
export const Property = (options: PropertyOptions): PropertyDecorator => {
  return (...args) => {
    console.log("Property", inspect(args));
    const [target, property] = args;
    const targetName = target.constructor.name;
    if (typeof property === "symbol") {
      throw new Error(`Symbol properties on ${targetName} are not supported`);
    }
    if (property === "type") {
      throw new Error(`Property name 'type' on '${targetName}' is reserved`);
    }
    let properties = PropertyContext.get(targetName);
    if (!properties) {
      properties = new Map();
      PropertyContext.set(targetName, properties);
    }
    properties.set(property, options);
  };
};

export abstract class DataModel {
  static isDataModel = true;

  static context() {
    return modelContextFrom(this.prototype.constructor);
  }

  context() {
    return modelContextFrom(this.constructor);
  }
}

@Model({
  name: "State",
  description: "A state object",
})
export class State extends DataModel {
  constructor(data?: DataModelInput<State>) {
    super();
    loadModel(this, data);
  }

  @Property({ type: String })
  key: string;

  @Property({ type: String })
  value: string;

  @Property({ converter: DateTimeValueConverter })
  createdAt: Temporal.Instant;

  @Property({ converter: DateTimeValueConverter })
  updatedAt: Temporal.Instant;
}
```

**Comment by WilliamABradley** [comment]
I found the transpiled source from tsx's cache:

<details><summary>Details</summary>
<p>

```js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __knownSymbol = (name, symbol) =>
  (symbol = Symbol[name]) ? symbol : Symbol.for("Symbol." + name);
var __typeError = (msg) => {
  throw TypeError(msg);
};
var __defNormalProp = (obj, key, value) =>
  key in obj
    ? __defProp(obj, key, {
        enumerable: true,
        configurable: true,
        writable: true,
        value,
      })
    : (obj[key] = value);
var __name = (target, value) =>
  __defProp(target, "name", { value, configurable: true });
var __decoratorStart = (base) => [
  ,
  ,
  ,
  __create(base?.[__knownSymbol("metadata")] ?? null),
];
var __decoratorStrings = [
  "class",
  "method",
  "getter",
  "setter",
  "accessor",
  "field",
  "value",
  "get",
  "set",
];
var __expectFn = (fn) =>
  fn !== void 0 && typeof fn !== "function"
    ? __typeError("Function expected")
    : fn;
var __decoratorContext = (kind, name, done, metadata, fns) => ({
  kind: __decoratorStrings[kind],
  name,
  metadata,
  addInitializer: (fn) =>
    done._
      ? __typeError("Already initialized")
      : fns.push(__expectFn(fn || null)),
});
var __decoratorMetadata = (array, target) =>
  __defNormalProp(target, __knownSymbol("metadata"), array[3]);
var __runInitializers = (array, flags, self, value) => {
  for (var i = 0, fns = array[flags >> 1], n = fns && fns.length; i < n; i++)
    flags & 1 ? fns[i].call(self) : (value = fns[i].call(self, value));
  return value;
};
var __decorateElement = (array, flags, name, decorators, target, extra) => {
  var fn,
    it,
    done,
    ctx,
    access,
    k = flags & 7,
    s = !!(flags & 8),
    p = !!(flags & 16);
  var j = k > 3 ? array.length + 1 : k ? (s ? 1 : 2) : 0,
    key = __decoratorStrings[k + 5];
  var initializers = k > 3 && (array[j - 1] = []),
    extraInitializers = array[j] || (array[j] = []);
  var desc =
    k &&
    (!p && !s && (target = target.prototype),
    k < 5 &&
      (k > 3 || !p) &&
      __getOwnPropDesc(
        k < 4
          ? target
          : {
              get [name]() {
                return __privateGet(this, extra);
              },
              set [name](x) {
                return __privateSet(this, extra, x);
              },
            },
        name
      ));
  k
    ? p && k < 4 && __name(extra, (k > 2 ? "set " : k > 1 ? "get " : "") + name)
    : __name(target, name);
  for (var i = decorators.length - 1; i >= 0; i--) {
    ctx = __decoratorContext(k, name, (done = {}), array[3], extraInitializers);
    if (k) {
      (ctx.static = s),
        (ctx.private = p),
        (access = ctx.access =
          { has: p ? (x) => __privateIn(target, x) : (x) => name in x });
      if (k ^ 3)
        access.get = p
          ? (x) =>
              (k ^ 1 ? __privateGet : __privateMethod)(
                x,
                target,
                k ^ 4 ? extra : desc.get
              )
          : (x) => x[name];
      if (k > 2)
        access.set = p
          ? (x, y) => __privateSet(x, target, y, k ^ 4 ? extra : desc.set)
          : (x, y) => (x[name] = y);
    }
    (it = (0, decorators[i])(
      k
        ? k < 4
          ? p
            ? extra
            : desc[key]
          : k > 4
          ? void 0
          : { get: desc.get, set: desc.set }
        : target,
      ctx
    )),
      (done._ = 1);
    if (k ^ 4 || it === void 0)
      __expectFn(it) &&
        (k > 4
          ? initializers.unshift(it)
          : k
          ? p
            ? (extra = it)
            : (desc[key] = it)
          : (target = it));
    else if (typeof it !== "object" || it === null)
      __typeError("Object expected");
    else
      __expectFn((fn = it.get)) && (desc.get = fn),
        __expectFn((fn = it.set)) && (desc.set = fn),
        __expectFn((fn = it.init)) && initializers.unshift(fn);
  }
  return (
    k || __decoratorMetadata(array, target),
    desc && __defProp(target, name, desc),
    p ? (k ^ 4 ? extra : desc) : target
  );
};
var __publicField = (obj, key, value) =>
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
var __accessCheck = (obj, member, msg) =>
  member.has(obj) || __typeError("Cannot " + msg);
var __privateIn = (member, obj) =>
  Object(obj) !== obj
    ? __typeError('Cannot use the "in" operator on this value')
    : member.has(obj);
var __privateGet = (obj, member, getter) => (
  __accessCheck(obj, member, "read from private field"),
  getter ? getter.call(obj) : member.get(obj)
);
var __privateSet = (obj, member, value, setter) => (
  __accessCheck(obj, member, "write to private field"),
  setter ? setter.call(obj, value) : member.set(obj, value),
  value
);
var __privateMethod = (obj, member, method) => (
  __accessCheck(obj, member, "access private method"), method
);
var _updatedAt_dec,
  _createdAt_dec,
  _value_dec,
  _key_dec,
  _a,
  _State_decorators,
  _init;
import {
  DataModel,
  DateTimeValueConverter,
  Model,
  OmitModel,
  Property,
  loadModel,
} from "#utils";
_State_decorators = [Model({ name: "State", description: "A state object" })];
let _State = class _State extends ((_a = DataModel),
(_key_dec = [Property({ type: String })]),
(_value_dec = [Property({ type: String })]),
(_createdAt_dec = [Property({ converter: DateTimeValueConverter })]),
(_updatedAt_dec = [Property({ converter: DateTimeValueConverter })]),
_a) {
  constructor(data) {
    super();
    __publicField(this, "key", __runInitializers(_init, 8, this)),
      __runInitializers(_init, 11, this);
    __publicField(this, "value", __runInitializers(_init, 12, this)),
      __runInitializers(_init, 15, this);
    __publicField(this, "createdAt", __runInitializers(_init, 16, this)),
      __runInitializers(_init, 19, this);
    __publicField(this, "updatedAt", __runInitializers(_init, 20, this)),
      __runInitializers(_init, 23, this);
    loadModel(this, data);
  }
};
_init = __decoratorStart(_a);
__decorateElement(_init, 5, "key", _key_dec, _State);
__decorateElement(_init, 5, "value", _value_dec, _State);
__decorateElement(_init, 5, "createdAt", _createdAt_dec, _State);
__decorateElement(_init, 5, "updatedAt", _updatedAt_dec, _State);
_State = __decorateElement(_init, 0, "State", _State_decorators, _State);
__name(_State, "State");
__runInitializers(_init, 1, _State);
let State = _State;
class UpdateState extends OmitModel(State, ["createdAt", "updatedAt"]) {
  static {
    __name(this, "UpdateState");
  }
  constructor(data) {
    super();
    loadModel(this, data);
  }
}
export { State, UpdateState };
```

</p>
</details> 

There must be something wrong with the esbuild flags that TSX is using, because this command seems to be working correctly: 

```
esbuild src/local.ts --bundle --outdir=out --format=esm --platform=node --banner:js="import { createRequire } from 'module'; const require = createRequire(import.meta.url);" --keep-names --target=node20.18.0 --minify-whitespace
```

**Comment by WilliamABradley** [comment]
I realise that my commands were bundling, while tsx was not.

This is what I got file I got from:

```
esbuild src/api/state.ts --outdir=out --format=esm --keep-names --target=node20.18.0 --minify-whitespace
```

<details><summary>Details</summary>
<p>

```js
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __name = (target, value) =>
  __defProp(target, "name", { value, configurable: true });
var __decorateClass = (decorators, target, key, kind) => {
  var result =
    kind > 1 ? void 0 : kind ? __getOwnPropDesc(target, key) : target;
  for (var i = decorators.length - 1, decorator; i >= 0; i--)
    if ((decorator = decorators[i]))
      result =
        (kind ? decorator(target, key, result) : decorator(result)) || result;
  if (kind && result) __defProp(target, key, result);
  return result;
};
import {
  DataModel,
  DateTimeValueConverter,
  Model,
  OmitModel,
  Property,
  loadModel,
} from "#utils";
let State = class extends DataModel {
  constructor(data) {
    super();
    loadModel(this, data);
  }
  key;
  value;
  createdAt;
  updatedAt;
};
__name(State, "State");
__decorateClass([Property({ type: String })], State.prototype, "key", 2);
__decorateClass([Property({ type: String })], State.prototype, "value", 2);
__decorateClass(
  [Property({ converter: DateTimeValueConverter })],
  State.prototype,
  "createdAt",
  2
);
__decorateClass(
  [Property({ converter: DateTimeValueConverter })],
  State.prototype,
  "updatedAt",
  2
);
State = __decorateClass(
  [Model({ name: "State", description: "A state object" })],
  State
);
class UpdateState extends OmitModel(State, ["createdAt", "updatedAt"]) {
  static {
    __name(this, "UpdateState");
  }
  constructor(data) {
    super();
    loadModel(this, data);
  }
}
export { State, UpdateState };
```

</p>
</details>

**Comment by WilliamABradley** [comment]
From what I can gather from the tsx source, this line is the culprit: https://github.com/evanw/esbuild/blob/9eca46464ed5615cb36a3beb3f7a7b9a8ffbe7cf/internal/runtime/runtime.go#L303

**Comment by juliennesme** [comment]
Hi, I ran in the exact same problem, narrowed it to this same line, but I don't understand why k (or flags in the __decorateElement function) equals 5 and it then strips the target... any news on this topic ?

**Comment by XinChou16** [comment]
Same Error, it's there any progress for this

**Comment by juliennesme** [comment]
I did work it arround, but not with one simple solution, just upgraded many things and changed confs in esbuild and tsconfig.json.
So i'll put some configs i'm using that seem to work now
esbuild :
const context = await esbuild.context({
    entryPoints: {
...
    },
    bundle: true,
    splitting: true,
    metafile: true,
    target: "es6",
    format: "esm",

    minify: !config.isdev,
    sourcemap: !!config.isdev,

    outdir: 'dist/public',
    outbase: 'src',
    publicPath: "/public",

    chunkNames: '[name]-[hash]-' + version,
    absWorkingDir: project_path,
    tsconfig: 'tsconfig.json',
});

tsconfig.json
{
    "compilerOptions": {
        "target": "es2020",
        "sourceMap": true,
        "module": "CommonJS",
        "importHelpers": true,
        "allowJs": true,
        "outDir": "dist/",
        "lib": [
            "es2020",
            "es6",
            "dom",
            "ESNext"
        ],
        "moduleResolution": "node",
        "types": [
            "node"
        ],
        "esModuleInterop": true,
        "emitDecoratorMetadata": true, // I think those are the 3 most important parameters to solve this issue
        "useDefineForClassFields": false, // I think those are the 3 most important parameters to solve this issue
        "experimentalDecorators": true // I think those are the 3 most important parameters to solve this issue
    },
    "include": [
        ...
    ],
    "exclude": [
        ...
    ]
}

using :
        "esbuild": "0.24.0",
        "typescript": "5.3.3",

Hope it helps. Had a very bad day with this one problem :)

**Comment by milesj** [comment]
Almost a year later and this seems to be an issue still.
