### ISSUE TITLE
ESBuild always fails with the signal SEGSEGV

### ISSUE THREAD

**Issue by solaritygh** [evanw/esbuild#4002]
[solarity@solarity-ms7c91 solarmath]$ npm i esbuild@0.18.0
npm error code 1
npm error path /run/media/solarity/Data/Documents/Github/solarmath/node_modules/esbuild
npm error command failed
npm error command sh -c node install.js
npm error node:internal/errors:983
npm error   const err = new Error(message);
npm error               ^
npm error
npm error Error: Command failed: /run/media/solarity/Data/Documents/Github/solarmath/node_modules/esbuild/bin/esbuild --version
npm error     at genericNodeError (node:internal/errors:983:15)
npm error     at wrappedFn (node:internal/errors:537:14)
npm error     at checkExecSyncError (node:child_process:882:11)
npm error     at Object.execFileSync (node:child_process:918:15)
npm error     at validateBinaryVersion (/run/media/solarity/Data/Documents/Github/solarmath/node_modules/esbuild/install.js:98:28)
npm error     at /run/media/solarity/Data/Documents/Github/solarmath/node_modules/esbuild/install.js:285:5 {
npm error   status: null,
npm error   signal: 'SIGSEGV',
npm error   output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
npm error   pid: 19202,
npm error   stdout: Buffer(0) [Uint8Array] [],
npm error   stderr: Buffer(0) [Uint8Array] []
npm error }
npm error
npm error Node.js v23.4.0
npm error A complete log of this run can be found in: /home/solarity/.npm/_logs/2024-12-14T14_06_55_858Z-debug-0.log
[solarity@solarity-ms7c91 solarmath]$ 

This happens with any package, and I'm seriously at a loss for what to do. I've been looking for solutions for DAYS. Nothing has worked.

Info:
[solarity@solarity-ms7c91 ~]$ neofetch
                     ./o.                  solarity@solarity-ms7c91 
                   ./sssso-                ------------------------ 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: MS-7C91 1.0 
             `-/ossssssssssssso/.          Kernel: 6.12.4-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 51 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1015 (pacman), 7 (flatpak) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.2.37 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080 
    .:///ossssssssssssssssssssssssso++:    DE: Plasma 6.2.4 
  `:////ssssssssssssssssssssssssssso+++.   WM: kwin 
`-////+ssssssssssssssssssssssssssso++++-   Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
 `..-+oosssssssssssssssssssssssso+++++/`   Icons: breeze-dark [GTK2/3] 
   ./++++++++++++++++++++++++++++++/:.     Terminal: konsole 
  `:::::::::::::::::::::::::------``       CPU: AMD Ryzen 7 5700X (16) @ 4.663GHz 
                                           GPU: NVIDIA Geforce RTX 3050 
                                           Memory: 7581MiB / 32019MiB

**Comment by evanw** [comment]
Sorry but this likely means the problem is on your end. You will have to debug this yourself. Since esbuild is a binary executable, it is platform-specific once installed.

Getting a SIGSEGV here likely means the version of esbuild that was installed by npm isn't for your current platform. This can happen in various situations such as when you run npm using a different OS and/or architecture than the one that esbuild runs with (e.g. when running Linux on Windows, or when running x86 npm on ARM macOS). The specifics of how to debug and fix this misconfiguration depends on the situation. The esbuild package uses node's `process.platform` and `os.arch()` APIs to determine what the appropriate platform is. It could be that this is misconfigured on your system.

It could also be that esbuild's executable is for the correct platform, but something about your configured OS cannot run the executable (I know nothing about Endeavour OS). You'd know whether that's the case or not if you download and compile esbuild yourself and even that doesn't work (install the Go compiler + git clone https://github.com/evanw/esbuild + `go build ./cmd/esbuild` + `./esbuild --version`). If that works then there's something wrong with your npm and you should be able to fix it. But if that doesn't work, then something is really wrong and esbuild may not work on your OS.

Another workaround is to use the `esbuild-wasm` package, which likely works if node works on your OS because the WASM file is interpreted by node instead of being executed by the OS.

And if you want to install esbuild such that it runs on more than one OS at once from the same directory tree, see these instructions: https://esbuild.github.io/getting-started/#simultaneous-platforms. In case that helps.
