### ISSUE TITLE
"No loader is configured" when using glob entrypoints with plugins

### ISSUE THREAD

**Issue by SystemParadox** [evanw/esbuild#4009]
See failing test case at https://github.com/SystemParadox/esbuild/tree/issue-plugin-glob-entrypoint.

This test works if the entrypoint is changed to `in.json5`, but using any kind of glob entrypoint results in:

```
✘ [ERROR] No loader is configured for ".json5" files
```

**Comment by kasir-barati** [comment]
Getting somewhat similar error message:

```bash
$ nx build bidirectional-grpc-file-upload --verbose

 NX   Running target build for project bidirectional-grpc-file-upload and 1 task it depends on:

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run shared:build  [local cache]


> nx run bidirectional-grpc-file-upload:build:production

✘ [ERROR] No loader is configured for ".proto" files: apps/bidirectional-grpc-file-upload/src/assets/file.proto


 NX   Build failed with 1 error:

error: No loader is configured for ".proto" files: apps/bidirectional-grpc-file-upload/src/assets/file.proto
Error: Build failed with 1 error:
error: No loader is configured for ".proto" files: apps/bidirectional-grpc-file-upload/src/assets/file.proto
    at failureErrorWithLog (/home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651:15)
    at /home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1059:25
    at /home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1004:52
    at buildResponseToResult (/home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1057:7)
    at /home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/home/kasir/projects/docker/docker-compose-files/minio/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
```

I have this monorepo setup which was working until I had to switch to pnpm workspaces and now it breaks down in the middle of compilation and bundling. I can also see that it is definitely able to copy over the `file.proto` as a pure asset without any issue but the mystery for me is that I am not importing the `file.proto` anywhere in my code, or at least I am not doing it directly (i.e. `import fileProto from '../assets/file.proto';` or something like that). So I am lost as to what should I do now:

Repo for reproducing this issue: https://github.com/kasir-barati/docker/tree/main/docker-compose-files/minio

@SystemParadox What did you do to solve you're issue?

@evanw @rtsao @magic-akari could you please confirm if this issue is related to esbuild or if it is something entirely different, and if it is can you please give me some pointers to find the cause of this issue and solve it (asking since the logs are all only about esbuild and I am not sure what's happening there 🙂)?

Thanks in advance ❤💮.

**Comment by SystemParadox** [comment]
@kasir-barati I don't think that has anything to do with this issue, which is specifically about glob imports. Please open your own issue.
