### ISSUE TITLE
panic: Scope location 3108304 must be greater than 3108315 [recovered]

### ISSUE THREAD

**Issue by timsuchanek** [evanw/esbuild#74]
This is the command:
```
esbuild build/index.js  --outdir=esbuild-output --bundle --platform=node
```

Gives me this error:
```
panic: Scope location 3108304 must be greater than 3108315 [recovered]
        panic: Scope location 3108304 must be greater than 3108315

goroutine 9 [running]:
esbuild/parser.Parse.func1(0xc00342da40)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:7827 +0x66
panic(0x1166020, 0xc0012a5220)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
esbuild/parser.(*parser).pushScopeForParsePass(0xc00008c000, 0x2, 0x2f6dd0, 0x1)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:272 +0x398
esbuild/parser.(*parser).parseParenExpr(0xc00008c000, 0x1002f6dd0, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:1759 +0x692
esbuild/parser.(*parser).parseAsyncExpr(0xc00008c000, 0x5002f6dd0, 0x1, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:1604 +0x391
esbuild/parser.(*parser).parsePrefix(0xc00008c000, 0x1, 0xc00342a780, 0xc000000000, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:1980 +0x2b31
esbuild/parser.(*parser).parseExprOrBindings(0xc00008c000, 0x1, 0xc00342a780, 0xc0031eb5c0, 0x4, 0x4)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2431 +0x43
esbuild/parser.(*parser).parseParenExpr(0xc00008c000, 0x2f6dcf, 0x924900000000, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:1689 +0x160
esbuild/parser.(*parser).parsePrefix(0xc00008c000, 0x3, 0x0, 0xc000000000, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:1915 +0x14b7
esbuild/parser.(*parser).parseExpr(0xc00008c000, 0x3, 0xc00342af60, 0x10c9554, 0xc000790dc6)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2435 +0x42
esbuild/parser.(*parser).parseSuffix(0xc00008c000, 0x2f6dc5, 0x11d7d80, 0xc0035531d0, 0x0, 0x0, 0x1177de0, 0xc00008c001, 0xc00350f720)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2872 +0x388c
esbuild/parser.(*parser).parseExpr(0xc00008c000, 0x0, 0xc0002f6db8, 0x11d7fc0, 0xc00350f700)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2435 +0x7f
esbuild/parser.(*parser).parseStmt(0xc00008c000, 0x1, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:4592 +0x113
esbuild/parser.(*parser).parseStmtsUpTo(0xc00008c000, 0x12, 0x1, 0xc0035531a0, 0xc0035540a0, 0x1)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:4834 +0xab
esbuild/parser.(*parser).parseFnBodyStmts(0xc00008c000, 0x0, 0x0, 0x0, 0x1)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:4817 +0xcb
esbuild/parser.(*parser).parseFn(0xc00008c000, 0x0, 0xc000000000, 0x0, 0xc0035531a0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:3529 +0x4bf
esbuild/parser.(*parser).parseFnExpr(0xc00008c000, 0x2f6dac, 0xc0002f6c98, 0x11d7da0, 0xc003556180)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:1651 +0xef
esbuild/parser.(*parser).parsePrefix(0xc00008c000, 0x1, 0xc00342c608, 0xc000000000, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2097 +0x2d80
esbuild/parser.(*parser).parseExprOrBindings(0xc00008c000, 0x1, 0xc00342c608, 0x2f6c98, 0x11d7da0, 0xc003556180)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2431 +0x43
esbuild/parser.(*parser).parseProperty(0xc00008c000, 0x0, 0x0, 0x0, 0xc00342c608, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:1430 +0x6b5
esbuild/parser.(*parser).parsePrefix(0xc00008c000, 0x1, 0x0, 0xc000000000, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2227 +0x6df
esbuild/parser.(*parser).parseExpr(0xc00008c000, 0x1, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2435 +0x42
esbuild/parser.(*parser).parseCallArgs(0xc00008c000, 0xc00049a023, 0x8, 0x1)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2933 +0x108
esbuild/parser.(*parser).parseSuffix(0xc00008c000, 0x23, 0x11d7da0, 0xc000078440, 0x3, 0x0, 0x118cce0, 0x1, 0xc00007a540)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2545 +0x235c
esbuild/parser.(*parser).parseExpr(0xc00008c000, 0x3, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2435 +0x7f
esbuild/parser.(*parser).parseSuffix(0xc00008c000, 0x14, 0x11d7d80, 0xc00007a540, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2872 +0x388c
esbuild/parser.(*parser).parseExpr(0xc00008c000, 0x0, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:2435 +0x7f
esbuild/parser.(*parser).parseStmt(0xc00008c000, 0x101, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:4592 +0x113
esbuild/parser.(*parser).parseStmtsUpTo(0xc00008c000, 0x0, 0x101, 0x36, 0xc0000161e8, 0xe)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:4834 +0xab
esbuild/parser.Parse(0xc000026120, 0x1, 0xc0000161c0, 0x36, 0xc0000161e8, 0xe, 0xc00049a000, 0x3299be, 0x1, 0xc00007a240, ...)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:7851 +0x1e0
esbuild/bundler.parseFile(0xc000026120, 0x1, 0xc0000161c0, 0x36, 0xc0000161e8, 0xe, 0xc00049a000, 0x3299be, 0x0, 0x0, ...)
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:61 +0x5e2
created by esbuild/bundler.ScanBundle.func2
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:168 +0x47c
```

## Reproduction

```
git clone git@github.com:prisma/prisma.git
cd prisma/src
npm i -g pnpm
pnpm i --ignore-scripts
pnpm run setup
cd packages/cli
esbuild build/index.js  --outdir=esbuild-output --bundle --platform=node
```

**Comment by evanw** [comment]
Thanks so much for the report. This assert has to do with the way the scope traversal needs to line up between the first and second parse passes. The parser only knows if a parenthesized expression is an arrow expression argument list after the closing parenthesis, but the scope for the arrow expression covers the whole parenthesized expression.

This is a minimal repro case:

```js
(x = () => {}) => {};
```

I'll look into fixing this tomorrow.
