### ISSUE TITLE
[Question / bug] Accessing .warnings and .errors from JS w/ plugins

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#745]
(Similar to #665)

I’m having trouble accessing the `.warnings` and `.errors` values when `plugins` is active, for the JS API. When `plugins` is inactive, this works as expected. But once I enable `plugins: [envPlugin]`, for example, I get `undefined; undefined`.

I assume this is because esbuild is exiting early, but I’m not sure how to capture the output still. I’ve been reading the JS source but I haven’t been able to figure this out for myself.

```js
// https://esbuild.github.io/plugins/#using-plugins
const envPlugin = {
	names: "env",
	setup(build) {
		// Intercept import paths called "env" so esbuild doesn't attempt
		// to map them to a file system location. Tag them with the "env-ns"
		// namespace to reserve them for this plugin.
		build.onResolve({ filter: /^env$/ }, args => ({
			path: args.path,
			namespace: "env-ns",
		}))
		// Load paths tagged with the "env-ns" namespace and behave as if
		// they point to a JSON file containing the environment variables.
		build.onLoad({ filter: /.*/, namespace: "env-ns" }, () => ({
			contents: JSON.stringify(process.env),
			loader: "json",
		}))
	},
}

require("esbuild")
	.build({
		bundle: true,
		entryPoints: ["app.js"],
		logLevel: "silent",
		outfile: "out.js",
		// plugins: [envPlugin], // <- Uncomment here
	})
	.catch(err => {
		console.log(err.errors)
		console.log(err.warnings)
	})
```

Expected output:

```
[
  {
    detail: undefined,
    location: {
      column: 7,
      file: 'app.js',
      length: 1,
      line: 1,
      lineText: 'imports{ PATH } from "env"'
    },
    text: 'Expected ";" but found "{"'
  }
]
[]
```

Actual output (when plugins are enabled):

```
undefined
undefined
```

**Comment by evanw** [comment]
What does the text of the error say? Is it perhaps not one of esbuild's errors? It's possible that a non-esbuild error was thrown and was captured by the promise.

**Comment by zaydek** [comment]
Well when I uncomment there is no error, at least esbuild returns `undefined`  and therefore there are no `.errors` or `.warnings` attached to the result. `silent` prevents the error from being logged to stderr but what I wanted is to interact with errors and warnings as a data structure.

I assume the plugin causes an internal error that isn’t passed back to the user.

**Comment by evanw** [comment]
If this code:

```js
	.catch(err => {
		console.log(err.errors)
		console.log(err.warnings)
	})
```

results in this output:

```
undefined
undefined
```

then presumably an error is being thrown somewhere and `err` is an object without the `errors` or `warnings` properties. It would be helpful for me to know what the error is to get a better idea of where it's coming from. Then I should be in a better position to do something about this problem.

**Comment by zaydek** [comment]
Sorry that wasn’t more useful. I created a minimum repro here https://github.com/zaydek/esbuild-plugin-behavior.

This is the [esbuild.js](https://github.com/zaydek/esbuild-plugin-behavior/blob/master/esbuild.js) file that describes what’s going on:

```js
// Command: node esbuild.js

// https://esbuild.github.io/plugins/#using-plugins
const envPlugin = {
	// Intentionally uses names instead of name to break esbuild; the intent is to
	// make sure esbuild emits errors whether or not plugins are being used.
	names: "env",
	setup(build) {
		build.onResolve({ filter: /^env$/ }, args => ({
			path: args.path,
			namespace: "env-ns",
		}))
		build.onLoad({ filter: /.*/, namespace: "env-ns" }, () => ({
			contents: JSON.stringify(process.env),
			loader: "json",
		}))
	},
}

require("esbuild")
	.build({
		bundle: true,
		entryPoints: ["in/app.js"],
		logLevel: "silent",
		outfile: "out/out.js",
		// plugins: [envPlugin],
	})
	.catch(err => {
		console.log({ err })
	})

// I get expected output when plugins are disabled (commented out). This is
// what I expect; the error is an object that has properties .errors and
// .warnings which I can use.
//
// {
//   err: Error: Build failed with 1 error:
//   in/app.js:1:7: error: Expected ";" but found "{"
//       at failureErrorWithLog (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:1124:15)
//       at buildResponseToResult (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:879:32)
//       at /Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:974:20
//       at /Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:541:9
//       at handleIncomingPacket (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:624:9)
//       at Socket.readFromStdout (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:508:7)
//       at Socket.emit (node:events:329:20)
//       at addChunk (node:internal/streams/readable:304:12)
//       at readableAddChunk (node:internal/streams/readable:279:9)
//       at Socket.Readable.push (node:internal/streams/readable:218:10) {
//     errors: [ [Object] ],
//     warnings: []
//   }
// }
//
// I get unexpected output when plugins are enabled. This is undesirable because
// I want to be able to introspect on .errors and .warnings.
//
// {
//   err: Error: Plugin at index 0 is missing a name
//       at handlePlugins (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:642:15)
//       at Object.buildOrServe (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:872:26)
//       at /Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:1344:17
//       at new Promise (<anonymous>)
//       at Object.build (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:1343:14)
//       at Object.build (/Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:1204:26)
//       at /Users/zaydek/github/retro-plugin-arch/node_modules/esbuild/lib/main.js:1252:67
//       at processTicksAndRejections (node:internal/process/task_queues:93:5)
// }
//
```

30 second version: the error passed by `catch` is simply an error string (when plugins are enabled). What I wanted / expect is to be able to introspect the error’s `.errors` and `.warnings` fields. Once plugins are enabled, I lose this granularity over the caught error.

Tested on 0.8.40.

**Comment by evanw** [comment]
Thanks for the detail. That makes it much more clear what's happening. At one point I was trying to funnel all validation errors through esbuild's general error function, but clearly that's not happening here. This is something to fix.

**Comment by zaydek** [comment]
Thank you Evan. I’m glad we’re synced up now. I’ll tag related issues for organizational purposes:

#665
#688

**Comment by zaydek** [comment]
Thank you!
