### ISSUE TITLE
Panic in esbuild.build

### ISSUE THREAD

**Issue by flunderpero** [evanw/esbuild#755]
In 0.8.41 I get this when I try to build:
```
panic: Internal error [recovered]
        panic: Internal error

goroutine 726 [running]:
github.com/evanw/esbuild/internal/js_parser.Parse.func1(0xc005c19e60)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:11889 +0x6a
panic(0x14083c0, 0x1503160)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmts(0xc007370000, 0xc0070df140, 0x5, 0x8, 0x144d300, 0xc0040824b0, 0x2, 0x3)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:6244 +0x148f
github.com/evanw/esbuild/internal/js_parser.(*parser).visitAndAppendStmt(0xc007370000, 0xc00299ee60, 0x0, 0x1, 0x67d, 0x150ae80, 0xc00722d5a0, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:7920 +0x6d7
github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmts(0xc007370000, 0xc005c160b8, 0x1, 0x1, 0xc007370000, 0xc00000062e, 0x150aaa0, 0xc0071d63c0)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:6233 +0x12ce
github.com/evanw/esbuild/internal/js_parser.(*parser).visitSingleStmt(0xc007370000, 0xc00000067d, 0x150ae80, 0xc00722d5a0, 0xc000000600, 0x150aaa0, 0xc0071d63c0, 0xc006d8e630)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:7049 +0xaf
github.com/evanw/esbuild/internal/js_parser.(*parser).visitAndAppendStmt(0xc007370000, 0xc006d8e630, 0x3, 0x6, 0x128c40000062b, 0x150b100, 0xc0071d6880, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:7974 +0x28ed
github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmts(0xc007370000, 0xc0070df2c0, 0x6, 0x8, 0xc000040902, 0xc006601600, 0x1302339, 0xc005c16c08)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:6233 +0x12ce
github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmtsAndPrependTempRefs(0xc007370000, 0xc0070df2c0, 0x6, 0x8, 0xc0071957c8, 0xc000000002, 0x150aaa0, 0xc007341b00, 0xc005c16c70)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:6152 +0xe5
github.com/evanw/esbuild/internal/js_parser.(*parser).visitFn(0xc007370000, 0xc0071957a0, 0x137)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:10874 +0x250
github.com/evanw/esbuild/internal/js_parser.(*parser).visitExprInOut(0xc007370000, 0xc000000137, 0x150ab40, 0xc0071957a0, 0xc000000000, 0x150aaa0, 0xc007341b40, 0xc000000000, 0x0, 0x0, ...)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:10739 +0xab51
github.com/evanw/esbuild/internal/js_parser.(*parser).visitExprInOut(0xc007370000, 0xc000000137, 0x150aae0, 0xc0071d6f80, 0x1ff00000000, 0xe1, 0x150aaa0, 0xc007341b80, 0x2000, 0x0, ...)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:10475 +0x5b85
github.com/evanw/esbuild/internal/js_parser.(*parser).visitExpr(0xc007370000, 0xc000000137, 0x150aae0, 0xc0071d6f80, 0xc00231cc60, 0x1, 0x1)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:9063 +0x56
github.com/evanw/esbuild/internal/js_parser.(*parser).visitAndAppendStmt(0xc007370000, 0xc00299e2a0, 0x0, 0x1, 0x136, 0x150b060, 0xc00722dce0, 0x0, 0x0, 0x0)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:7886 +0x4cde
github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmts(0xc007370000, 0xc00299e220, 0x1, 0x1, 0x146c900, 0x1d8, 0x1e0, 0xc478a30)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:6233 +0x12ce
github.com/evanw/esbuild/internal/js_parser.(*parser).visitStmtsAndPrependTempRefs(0xc007370000, 0xc00299e220, 0x1, 0x1, 0x0, 0xc002ec2f00, 0x2, 0x4, 0x1)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:6152 +0xe5
github.com/evanw/esbuild/internal/js_parser.(*parser).appendPart(0xc007370000, 0xc002ec2f00, 0x3, 0x4, 0xc00299e220, 0x1, 0x1, 0xc002ec2f00, 0x3, 0x4)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:11319 +0xf7
github.com/evanw/esbuild/internal/js_parser.Parse(0xc007346140, 0xc007346160, 0xc007346180, 0x299, 0xc0062e41e0, 0x43, 0x1487540, 0x4, 0xc0062e4200, 0x23, ...)
        /Users/evan/dev/esbuild/internal/js_parser/js_parser.go:12006 +0xb8d
github.com/evanw/esbuild/internal/cache.(*JSCache).Parse(0xc0001a8048, 0xc000180050, 0xc000196040, 0xc0001a4000, 0x299, 0xc0062e41e0, 0x43, 0x1487540, 0x4, 0xc0062e4200, ...)
        /Users/evan/dev/esbuild/internal/cache/cache_ast.go:170 +0x298
github.com/evanw/esbuild/internal/bundler.parseFile(0x1513d40, 0xc000184240, 0xc000180050, 0xc000196040, 0xc0001a4000, 0x15111e0, 0xc0001c0280, 0xc0001a8000, 0xc0062e41e0, 0x43, ...)
        /Users/evan/dev/esbuild/internal/bundler/bundler.go:223 +0x1d9e
created by github.com/evanw/esbuild/internal/bundler.(*scanner).maybeParseFile
        /Users/evan/dev/esbuild/internal/bundler/bundler.go:938 +0x518
Error: The service was stopped
    at /Users/pero/src/pero/cling-main/node_modules/esbuild/lib/main.js:953:31
    at /Users/pero/src/pero/cling-main/node_modules/esbuild/lib/main.js:541:9
    at Socket.afterClose (/Users/pero/src/pero/cling-main/node_modules/esbuild/lib/main.js:519:7)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/
```

In 0.8.40 everything's fine.

I am using the JS-API like this:
```
    await esbuild.build({
        entryPoints: [
            "path-to-my-main-entry"
        ],
        outdir: "some dir",
        outExtension: {".js": ".mjs"},
        loader: {
            ".proto": "file",
        },
        footer: "app.start()",
        format: "esm",
        platform: "node",
        tsconfig: "path to a tsconfig",
        metafile: "some path",
        define: {
           ...
        },
        sourcemap: "external",
        minifyIdentifiers: false,
        minifySyntax: false,
        minifyWhitespace: false,
        bundle: true,
        keepNames: true,
        target: "es2017"
    })
```

I hope this information is enough to get you on the right path.

**Comment by flunderpero** [comment]
Wow, Evan, you're quick!
