### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Must run at most one command

### ISSUE THREAD

**Issue by daniel-sudz** [evanw/esbuild#784]
I'm getting this warning occasionally and I'm unable to reproduce it consistently. Sometimes the error throws with the same build command while sometimes it does not. The build seems to always work however without a problem. 

```
(node:93570) UnhandledPromiseRejectionWarning: Error: Must run at most one command
    at Object.writeToStdin (/[Redacted]/node_modules/esbuild/lib/main.js:1422:15)
    at sendResponse (/[Redacted]/node_modules/esbuild/lib/main.js:563:14)
    at /[Redacted]/node_modules/esbuild/lib/main.js:617:7
    at Generator.next (<anonymous>)
    at /[Redacted]/node_modules/esbuild/lib/main.js:27:61
    at new Promise (<anonymous>)
    at __async (/[Redacted]/node_modules/esbuild/lib/main.js:9:10)
    at handleRequest (/[Redacted]/node_modules/esbuild/lib/main.js:565:40)
    at handleIncomingPacket (/[Redacted]/node_modules/esbuild/lib/main.js:632:7)
    at readFromStdout (/[Redacted]/node_modules/esbuild/lib/main.js:517:7)
```

This is the build command that I'm using: 

```
const build = (inputPath: string, outputName: string) => {
  esbuild.buildSync({
    entryPoints: [path.resolve("../../", inputPath)],
    bundle: true,
    target: "esnext",
    platform: "node",
    outfile: `./bundles/${outputName}`,
    external: ["protobufjs"], 
  });
};
```

The buildSync commands runs several times within a for loop.

**Comment by evanw** [comment]
Thanks for the report. I suspect this is a regression that I introduced in version 0.8.39 when I fixed #643. The child process now periodically pings the host process and will exit if the ping doesn't go through to avoid becoming a dangling child process. I think the response from the ping is being incorrectly counted as a second command.
