### ISSUE TITLE
crash when parsing glsl with text loader

### ISSUE THREAD

**Issue by frading** [evanw/esbuild#89]
Hello,

This seems fantastically fast!

That said, I could not yet compile my project in full, as esbuild crashed. Here is the output I see:

```
panic: (lexer.LexerPanic) (0x56cd20,0x6e9cb0)

goroutine 12 [running]:
esbuild/lexer.(*Lexer).SyntaxError(0xc0000534b8)
        /Users/evan/dev/esbuild/src/esbuild/lexer/lexer.go:320 +0x2e9
esbuild/lexer.(*Lexer).Next(0xc0000534b8)
        /Users/evan/dev/esbuild/src/esbuild/lexer/lexer.go:830 +0x8da
esbuild/lexer.NewLexer(0xc0000202a0, 0x2, 0xc000022230, 0x4b, 0xc00002225f, 0x1c, 0xc0001680c0, 0xb4, 0x0, 0x0, ...)
        /Users/evan/dev/esbuild/src/esbuild/lexer/lexer.go:247 +0xca
esbuild/parser.newParser(0xc0000202a0, 0x2, 0xc000022230, 0x4b, 0xc00002225f, 0x1c, 0xc0001680c0, 0xb4, 0x1, 0xc00006e2d0, ...)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:8341 +0x77
esbuild/parser.ModuleExportsAST(0xc0000202a0, 0x2, 0xc000022230, 0x4b, 0xc00002225f, 0x1c, 0xc0001680c0, 0xb4, 0x1, 0xc00006e2d0, ...)
        /Users/evan/dev/esbuild/src/esbuild/parser/parser.go:8460 +0xc6
esbuild/bundler.parseFile(0xc0000202a0, 0x2, 0xc000022230, 0x4b, 0xc00002225f, 0x1c, 0xc0001680c0, 0xb4, 0x1, 0xc0000220f0, ...)
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:88 +0xc34
created by esbuild/bundler.ScanBundle.func2
        /Users/evan/dev/esbuild/src/esbuild/bundler/bundler.go:169 +0x48f
```

Here is how to reproduce it:

``` bash
git clone https://github.com/polygonjs/polygonjs-engine.git;
cd polygonjs-engine;
git checkout esbuild;
yarn;
node_modules/esbuild/bin/esbuild src/engine/esbuild_error.ts --bundle '--define:process.env.NODE_ENV="development"' --loader:.glsl=text --outfile=out.js;
```

On some runs, the error is explicit:
```
src/engine/shader_error.glsl:1:0: error: Syntax error "#"
#include <common>
```
Even though I'd expect the text loader to not have problems with such lines.

But it's worth noting that this error message is not always printed out. On many occasions, all I see is the stack trace, so I can only find the error source by excluding modules gradually.

And the following command that could compile the whole project always crashes:
```
node_modules/esbuild/bin/esbuild src/engine/index.ts --bundle '--define:process.env.NODE_ENV="development"' --loader:.glsl=text --outfile=out.js
```

Don't hesitate to let me know if you'd like more info to help debug this.

**Comment by evanw** [comment]
Thanks for reporting this issue. Sorry about that. This was due to a bug where the first token of text files was being parsed. It should be fixed now. Please let me know if you find any other issues.

**Comment by frading** [comment]
Great! Thank you so much for the quick response.
